/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lineup.view;

import br.com.lineup.controller.ControllerCliente;
import br.com.lineup.controller.ControllerOrdem_de_Serviço;
import br.com.lineup.model.ModelCliente;
import br.com.lineup.model.ModelOrdem_de_Serviço;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siqueira
 */
public class HOME extends javax.swing.JFrame {

    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelClientes = new ArrayList<>();

    ControllerOrdem_de_Serviço controllerOrdem_de_Serviço = new ControllerOrdem_de_Serviço();
    ModelOrdem_de_Serviço modelOrdem_de_Serviço = new ModelOrdem_de_Serviço();
    ArrayList<ModelOrdem_de_Serviço> listaModelOrdem_de_Serviços = new ArrayList<>();

    /**
     * Creates new form HOME
     */
    public HOME() {
        initComponents();
        //setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        new Trocar_Painel(Painel_desktop, new Tela_Home());
        Busca_OS();
    }

    private void Busca_OS() {
        listaModelOrdem_de_Serviços = controllerOrdem_de_Serviço.getListaOrdem_de_ServiçoController();
        listaModelClientes = controllerCliente.getListaClienteController();
        DefaultTableModel tabela = (DefaultTableModel) Tela_Home.tabelaOS.getModel();
        tabela.setNumRows(0);

        int tam_lista = listaModelOrdem_de_Serviços.size();
        for (int i = 0; i < tam_lista; i++) {
            tabela.addRow(new Object[]{
                listaModelOrdem_de_Serviços.get(i).getOs(),
                listaModelOrdem_de_Serviços.get(i).getDataos(),
                listaModelOrdem_de_Serviços.get(i).getStatusOS(),
                listaModelOrdem_de_Serviços.get(i).getAparelho(),
                listaModelOrdem_de_Serviços.get(i).getDefeito(),
                listaModelOrdem_de_Serviços.get(i).getServico(),
                listaModelOrdem_de_Serviços.get(i).getTecnico(),
                listaModelOrdem_de_Serviços.get(i).getValorservico(),
                listaModelOrdem_de_Serviços.get(i).getId_cli(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Painel_Opções = new javax.swing.JPanel();
        btn_Menu = new javax.swing.JButton();
        Painel_desktop = new javax.swing.JPanel();
        Painel_Opções4 = new javax.swing.JPanel();
        rSButtonMetro2 = new rsbuttom.RSButtonMetro();
        lbl_Usuário = new javax.swing.JLabel();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        Painel_Menu = new javax.swing.JPanel();
        btn_Funcionários = new rojerusan.RSButtonPane();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btn_Home = new rojerusan.RSButtonPane();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btn_Serviços = new rojerusan.RSButtonPane();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btn_Produtos = new rojerusan.RSButtonPane();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btn_Fornecedores = new rojerusan.RSButtonPane();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btn_Clientes = new rojerusan.RSButtonPane();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        btn_Relatórios = new rojerusan.RSButtonPane();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btn_OS = new rojerusan.RSButtonPane();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        btn_Vendas = new rojerusan.RSButtonPane();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Painel_Opções.setBackground(new java.awt.Color(0, 66, 109));

        btn_Menu.setBackground(new java.awt.Color(0, 66, 109));
        btn_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Menu.png"))); // NOI18N
        btn_Menu.setContentAreaFilled(false);
        btn_Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_OpçõesLayout = new javax.swing.GroupLayout(Painel_Opções);
        Painel_Opções.setLayout(Painel_OpçõesLayout);
        Painel_OpçõesLayout.setHorizontalGroup(
            Painel_OpçõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_OpçõesLayout.createSequentialGroup()
                .addComponent(btn_Menu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_OpçõesLayout.setVerticalGroup(
            Painel_OpçõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Painel_desktop.setBackground(new java.awt.Color(255, 255, 255));
        Painel_desktop.setLayout(new java.awt.BorderLayout());

        Painel_Opções4.setBackground(new java.awt.Color(0, 66, 109));

        rSButtonMetro2.setBackground(new java.awt.Color(0, 66, 109));
        rSButtonMetro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Usuário logado.png"))); // NOI18N
        rSButtonMetro2.setColorHover(new java.awt.Color(51, 255, 0));
        rSButtonMetro2.setColorNormal(new java.awt.Color(0, 66, 109));
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });

        lbl_Usuário.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbl_Usuário.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Usuário.setText("USUÁRIO");

        rSButtonMetro1.setBackground(new java.awt.Color(0, 66, 109));
        rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Logout_32px.png"))); // NOI18N
        rSButtonMetro1.setColorHover(new java.awt.Color(255, 153, 0));
        rSButtonMetro1.setColorNormal(new java.awt.Color(0, 66, 109));
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_Opções4Layout = new javax.swing.GroupLayout(Painel_Opções4);
        Painel_Opções4.setLayout(Painel_Opções4Layout);
        Painel_Opções4Layout.setHorizontalGroup(
            Painel_Opções4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Opções4Layout.createSequentialGroup()
                .addComponent(rSButtonMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Usuário)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Painel_Opções4Layout.setVerticalGroup(
            Painel_Opções4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Opções4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Painel_Opções4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButtonMetro2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Usuário, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Painel_Menu.setBackground(new java.awt.Color(0, 66, 109));

        btn_Funcionários.setBackground(new java.awt.Color(0, 102, 153));
        btn_Funcionários.setColorHover(new java.awt.Color(0, 66, 109));
        btn_Funcionários.setColorNormal(new java.awt.Color(0, 102, 153));
        btn_Funcionários.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_FuncionáriosMouseClicked(evt);
            }
        });

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Funcionários.png"))); // NOI18N

        jLabel32.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("FUNCIONÁRIOS");

        javax.swing.GroupLayout btn_FuncionáriosLayout = new javax.swing.GroupLayout(btn_Funcionários);
        btn_Funcionários.setLayout(btn_FuncionáriosLayout);
        btn_FuncionáriosLayout.setHorizontalGroup(
            btn_FuncionáriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_FuncionáriosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        btn_FuncionáriosLayout.setVerticalGroup(
            btn_FuncionáriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_Home.setBackground(new java.awt.Color(0, 102, 153));
        btn_Home.setColorHover(new java.awt.Color(0, 66, 109));
        btn_Home.setColorNormal(new java.awt.Color(0, 102, 153));
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HomeMouseClicked(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Home.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("HOME");

        javax.swing.GroupLayout btn_HomeLayout = new javax.swing.GroupLayout(btn_Home);
        btn_Home.setLayout(btn_HomeLayout);
        btn_HomeLayout.setHorizontalGroup(
            btn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_HomeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        btn_HomeLayout.setVerticalGroup(
            btn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_Serviços.setBackground(new java.awt.Color(0, 102, 153));
        btn_Serviços.setColorHover(new java.awt.Color(0, 66, 109));
        btn_Serviços.setColorNormal(new java.awt.Color(0, 102, 153));
        btn_Serviços.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ServiçosMouseClicked(evt);
            }
        });

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Serviços.png"))); // NOI18N

        jLabel34.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("SERVIÇOS");

        javax.swing.GroupLayout btn_ServiçosLayout = new javax.swing.GroupLayout(btn_Serviços);
        btn_Serviços.setLayout(btn_ServiçosLayout);
        btn_ServiçosLayout.setHorizontalGroup(
            btn_ServiçosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ServiçosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        btn_ServiçosLayout.setVerticalGroup(
            btn_ServiçosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_Produtos.setBackground(new java.awt.Color(0, 102, 153));
        btn_Produtos.setColorHover(new java.awt.Color(0, 66, 109));
        btn_Produtos.setColorNormal(new java.awt.Color(0, 102, 153));
        btn_Produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ProdutosMouseClicked(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Produtos.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("PRODUTOS");

        javax.swing.GroupLayout btn_ProdutosLayout = new javax.swing.GroupLayout(btn_Produtos);
        btn_Produtos.setLayout(btn_ProdutosLayout);
        btn_ProdutosLayout.setHorizontalGroup(
            btn_ProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ProdutosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        btn_ProdutosLayout.setVerticalGroup(
            btn_ProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_Fornecedores.setBackground(new java.awt.Color(0, 102, 153));
        btn_Fornecedores.setColorHover(new java.awt.Color(0, 66, 109));
        btn_Fornecedores.setColorNormal(new java.awt.Color(0, 102, 153));
        btn_Fornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_FornecedoresMouseClicked(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Fornecedores.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("FORNECEDORES");

        javax.swing.GroupLayout btn_FornecedoresLayout = new javax.swing.GroupLayout(btn_Fornecedores);
        btn_Fornecedores.setLayout(btn_FornecedoresLayout);
        btn_FornecedoresLayout.setHorizontalGroup(
            btn_FornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_FornecedoresLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        btn_FornecedoresLayout.setVerticalGroup(
            btn_FornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_Clientes.setBackground(new java.awt.Color(0, 102, 153));
        btn_Clientes.setColorHover(new java.awt.Color(0, 66, 109));
        btn_Clientes.setColorNormal(new java.awt.Color(0, 102, 153));
        btn_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ClientesMouseClicked(evt);
            }
        });
        btn_Clientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_ClientesKeyPressed(evt);
            }
        });

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Clientes.png"))); // NOI18N

        jLabel36.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("CLIENTES");

        javax.swing.GroupLayout btn_ClientesLayout = new javax.swing.GroupLayout(btn_Clientes);
        btn_Clientes.setLayout(btn_ClientesLayout);
        btn_ClientesLayout.setHorizontalGroup(
            btn_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ClientesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        btn_ClientesLayout.setVerticalGroup(
            btn_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_Relatórios.setBackground(new java.awt.Color(0, 102, 153));
        btn_Relatórios.setColorHover(new java.awt.Color(0, 66, 109));
        btn_Relatórios.setColorNormal(new java.awt.Color(0, 102, 153));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Relatórios.png"))); // NOI18N

        jLabel30.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("RELATÓRIOS");

        javax.swing.GroupLayout btn_RelatóriosLayout = new javax.swing.GroupLayout(btn_Relatórios);
        btn_Relatórios.setLayout(btn_RelatóriosLayout);
        btn_RelatóriosLayout.setHorizontalGroup(
            btn_RelatóriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_RelatóriosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        btn_RelatóriosLayout.setVerticalGroup(
            btn_RelatóriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/LineUp Logo.png"))); // NOI18N
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_OS.setBackground(new java.awt.Color(0, 102, 153));
        btn_OS.setColorHover(new java.awt.Color(0, 66, 109));
        btn_OS.setColorNormal(new java.awt.Color(0, 102, 153));
        btn_OS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_OSMouseClicked(evt);
            }
        });

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Ordem de Serviço.png"))); // NOI18N

        jLabel38.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("ORDEM DE SERVIÇO");

        javax.swing.GroupLayout btn_OSLayout = new javax.swing.GroupLayout(btn_OS);
        btn_OS.setLayout(btn_OSLayout);
        btn_OSLayout.setHorizontalGroup(
            btn_OSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_OSLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        btn_OSLayout.setVerticalGroup(
            btn_OSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_Vendas.setBackground(new java.awt.Color(0, 102, 153));
        btn_Vendas.setColorHover(new java.awt.Color(0, 66, 109));
        btn_Vendas.setColorNormal(new java.awt.Color(0, 102, 153));
        btn_Vendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_VendasMouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Vendas.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("VENDAS");

        javax.swing.GroupLayout btn_VendasLayout = new javax.swing.GroupLayout(btn_Vendas);
        btn_Vendas.setLayout(btn_VendasLayout);
        btn_VendasLayout.setHorizontalGroup(
            btn_VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_VendasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        btn_VendasLayout.setVerticalGroup(
            btn_VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Painel_MenuLayout = new javax.swing.GroupLayout(Painel_Menu);
        Painel_Menu.setLayout(Painel_MenuLayout);
        Painel_MenuLayout.setHorizontalGroup(
            Painel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Vendas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_Funcionários, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_Fornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_Produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_Serviços, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_OS, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_Relatórios, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Painel_MenuLayout.setVerticalGroup(
            Painel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_MenuLayout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Funcionários, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Fornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Serviços, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_OS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Vendas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Relatórios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Painel_Opções, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Painel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Painel_Opções4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Painel_desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Painel_Opções, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Painel_Opções4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Painel_desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Painel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed
        // TODO add your handling code here:
        Informações_Usuário user = new Informações_Usuário();
        user.setVisible(true); 
    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        // TODO add your handling code here:
        int logout = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja fazer Logout?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (logout == JOptionPane.YES_OPTION) {
            Tela_Login login = new Tela_Login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed
        // TODO add your handling code here:
        int posição = this.Painel_Menu.getX();
        if (posição > -1) {
            Animacion.Animacion.mover_izquierda(0, -250, 2, 2, Painel_Menu);
        } else {
            Animacion.Animacion.mover_derecha(-250, 0, 2, 2, Painel_Menu);
        }
    }//GEN-LAST:event_btn_MenuActionPerformed

    private void btn_FornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FornecedoresMouseClicked
        // TODO add your handling code here:
        new Trocar_Painel(Painel_desktop, new Tela_Fornecedores());
    }//GEN-LAST:event_btn_FornecedoresMouseClicked

    private void btn_VendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_VendasMouseClicked
        // TODO add your handling code here:
        Tela_Vendas vendas = new Tela_Vendas();
        vendas.setVisible(true); 
    }//GEN-LAST:event_btn_VendasMouseClicked

    private void btn_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseClicked
        // TODO add your handling code here:
        new Trocar_Painel(Painel_desktop, new Tela_Home());
    }//GEN-LAST:event_btn_HomeMouseClicked

    private void btn_ProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ProdutosMouseClicked
        // TODO add your handling code here:
        new Trocar_Painel(Painel_desktop, new Tela_Produtos());
    }//GEN-LAST:event_btn_ProdutosMouseClicked

    private void btn_FuncionáriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FuncionáriosMouseClicked
        // TODO add your handling code here:
        new Trocar_Painel(Painel_desktop, new Tela_Funcionários());
    }//GEN-LAST:event_btn_FuncionáriosMouseClicked

    private void btn_ServiçosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ServiçosMouseClicked
        // TODO add your handling code here:
        Tela_Serviços serviço = new Tela_Serviços();
        serviço.setVisible(true); 
    }//GEN-LAST:event_btn_ServiçosMouseClicked

    private void btn_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ClientesMouseClicked
        // TODO add your handling code here:
        new Trocar_Painel(Painel_desktop, new Tela_Cliente());
    }//GEN-LAST:event_btn_ClientesMouseClicked

    private void btn_ClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_ClientesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ClientesKeyPressed

    private void btn_OSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_OSMouseClicked
        // TODO add your handling code here:
        new Trocar_Painel(Painel_desktop, new Tela_OS());
    }//GEN-LAST:event_btn_OSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_Menu;
    private javax.swing.JPanel Painel_Opções;
    private javax.swing.JPanel Painel_Opções4;
    public static javax.swing.JPanel Painel_desktop;
    public static rojerusan.RSButtonPane btn_Clientes;
    public static rojerusan.RSButtonPane btn_Fornecedores;
    public static rojerusan.RSButtonPane btn_Funcionários;
    public static rojerusan.RSButtonPane btn_Home;
    private javax.swing.JButton btn_Menu;
    public static rojerusan.RSButtonPane btn_OS;
    public static rojerusan.RSButtonPane btn_Produtos;
    public static rojerusan.RSButtonPane btn_Relatórios;
    public static rojerusan.RSButtonPane btn_Serviços;
    public static rojerusan.RSButtonPane btn_Vendas;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lbl_Usuário;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    public static rsbuttom.RSButtonMetro rSButtonMetro2;
    // End of variables declaration//GEN-END:variables
}
