/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lineup.view;

import br.com.lineup.controller.ControllerCliente;
import br.com.lineup.controller.ControllerOrdem_de_Serviço;
import br.com.lineup.model.ModelCliente;
import br.com.lineup.model.ModelOrdem_de_Serviço;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siqueira
 */
public class Principal extends javax.swing.JFrame {

    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelClientes = new ArrayList<>();

    ControllerOrdem_de_Serviço controllerOrdem_de_Serviço = new ControllerOrdem_de_Serviço();
    ModelOrdem_de_Serviço modelOrdem_de_Serviço = new ModelOrdem_de_Serviço();
    ArrayList<ModelOrdem_de_Serviço> listaModelOrdem_de_Serviços = new ArrayList<>();

    /**
     * Creates new form HOME
     */
    public Principal() {
        initComponents();
        //setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        //new Trocar_Painel(Painel_desktop, new Tela_Home());
        //Busca_OS();
    }

    private void Busca_OS() {
        listaModelOrdem_de_Serviços = controllerOrdem_de_Serviço.getListaOrdem_de_ServiçoController();
        listaModelClientes = controllerCliente.getListaClienteController();
        DefaultTableModel tabela = (DefaultTableModel) Tela_Home.tabelaOS.getModel();
        tabela.setNumRows(0);

        int tam_lista = listaModelOrdem_de_Serviços.size();
        for (int i = 0; i < tam_lista; i++) {
            tabela.addRow(new Object[]{
                listaModelOrdem_de_Serviços.get(i).getOs(),
                listaModelOrdem_de_Serviços.get(i).getDataos(),
                listaModelOrdem_de_Serviços.get(i).getStatusOS(),
                listaModelOrdem_de_Serviços.get(i).getAparelho(),
                listaModelOrdem_de_Serviços.get(i).getDefeito(),
                listaModelOrdem_de_Serviços.get(i).getServico(),
                listaModelOrdem_de_Serviços.get(i).getTecnico(),
                listaModelOrdem_de_Serviços.get(i).getValorservico(),
                listaModelOrdem_de_Serviços.get(i).getId_cli(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Painel_Opções = new javax.swing.JPanel();
        btn_Menu = new javax.swing.JButton();
        Painel_desktop = new javax.swing.JPanel();
        Painel_Opções4 = new javax.swing.JPanel();
        rSButtonMetro2 = new rsbuttom.RSButtonMetro();
        lbl_Usuário = new javax.swing.JLabel();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        Painel_Menu = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        rSButtonMetro4 = new rsbuttom.RSButtonMetro();
        rSButtonMetro5 = new rsbuttom.RSButtonMetro();
        rSButtonMetro6 = new rsbuttom.RSButtonMetro();
        rSButtonMetro7 = new rsbuttom.RSButtonMetro();
        rSButtonMetro8 = new rsbuttom.RSButtonMetro();
        rSButtonMetro9 = new rsbuttom.RSButtonMetro();
        rSButtonMetro10 = new rsbuttom.RSButtonMetro();
        rSButtonMetro11 = new rsbuttom.RSButtonMetro();
        rSButtonMetro12 = new rsbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Painel_Opções.setBackground(new java.awt.Color(0, 66, 109));

        btn_Menu.setBackground(new java.awt.Color(0, 66, 109));
        btn_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Menu.png"))); // NOI18N
        btn_Menu.setContentAreaFilled(false);
        btn_Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_OpçõesLayout = new javax.swing.GroupLayout(Painel_Opções);
        Painel_Opções.setLayout(Painel_OpçõesLayout);
        Painel_OpçõesLayout.setHorizontalGroup(
            Painel_OpçõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_OpçõesLayout.createSequentialGroup()
                .addComponent(btn_Menu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_OpçõesLayout.setVerticalGroup(
            Painel_OpçõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Painel_desktop.setBackground(new java.awt.Color(0, 0, 0));
        Painel_desktop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Painel_Opções4.setBackground(new java.awt.Color(0, 66, 109));

        rSButtonMetro2.setBackground(new java.awt.Color(0, 66, 109));
        rSButtonMetro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Usuário logado.png"))); // NOI18N
        rSButtonMetro2.setColorHover(new java.awt.Color(51, 255, 0));
        rSButtonMetro2.setColorNormal(new java.awt.Color(0, 66, 109));
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });

        lbl_Usuário.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbl_Usuário.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Usuário.setText("USUÁRIO");

        rSButtonMetro1.setBackground(new java.awt.Color(0, 66, 109));
        rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Logout_32px.png"))); // NOI18N
        rSButtonMetro1.setColorHover(new java.awt.Color(255, 153, 0));
        rSButtonMetro1.setColorNormal(new java.awt.Color(0, 66, 109));
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_Opções4Layout = new javax.swing.GroupLayout(Painel_Opções4);
        Painel_Opções4.setLayout(Painel_Opções4Layout);
        Painel_Opções4Layout.setHorizontalGroup(
            Painel_Opções4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Opções4Layout.createSequentialGroup()
                .addComponent(rSButtonMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Usuário)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 600, Short.MAX_VALUE)
                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Painel_Opções4Layout.setVerticalGroup(
            Painel_Opções4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Opções4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Painel_Opções4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButtonMetro2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Usuário, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Painel_Menu.setBackground(new java.awt.Color(0, 66, 109));
        Painel_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/LineUp Logo.png"))); // NOI18N
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Painel_Menu.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 79));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Funcionários.png"))); // NOI18N
        Painel_Menu.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 50));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("FORNECEDORES");
        Painel_Menu.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 50));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Clientes.png"))); // NOI18N
        Painel_Menu.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 50));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Home.png"))); // NOI18N
        Painel_Menu.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 50));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("HOME");
        Painel_Menu.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 50));

        jLabel38.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("ORDEM DE SERVIÇO");
        Painel_Menu.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, 50));

        jLabel32.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("FUNCIONÁRIOS");
        Painel_Menu.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 50));

        jLabel36.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("CLIENTES");
        Painel_Menu.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 50));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Fornecedores.png"))); // NOI18N
        Painel_Menu.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 50));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("PRODUTOS");
        Painel_Menu.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 50));

        jLabel34.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("SERVIÇOS");
        Painel_Menu.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, 50));

        jLabel30.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("RELATÓRIOS");
        Painel_Menu.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, 50));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Produtos.png"))); // NOI18N
        Painel_Menu.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 50));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("VENDAS");
        Painel_Menu.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, 50));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Serviços.png"))); // NOI18N
        Painel_Menu.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 50));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Ordem de Serviço.png"))); // NOI18N
        Painel_Menu.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 50));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Vendas.png"))); // NOI18N
        Painel_Menu.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, 50));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Relatórios.png"))); // NOI18N
        Painel_Menu.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, 50));

        rSButtonMetro4.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonMetro4.setColorHover(new java.awt.Color(0, 66, 109));
        rSButtonMetro4.setColorNormal(new java.awt.Color(0, 102, 153));
        rSButtonMetro4.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rSButtonMetro4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro4.setIconTextGap(20);
        rSButtonMetro4.setMargin(new java.awt.Insets(2, 1000, 2, 14));
        Painel_Menu.add(rSButtonMetro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 50));

        rSButtonMetro5.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonMetro5.setColorHover(new java.awt.Color(0, 66, 109));
        rSButtonMetro5.setColorNormal(new java.awt.Color(0, 102, 153));
        rSButtonMetro5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro5.setIconTextGap(20);
        Painel_Menu.add(rSButtonMetro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 50));

        rSButtonMetro6.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonMetro6.setColorHover(new java.awt.Color(0, 66, 109));
        rSButtonMetro6.setColorNormal(new java.awt.Color(0, 102, 153));
        rSButtonMetro6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro6.setIconTextGap(20);
        Painel_Menu.add(rSButtonMetro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 50));

        rSButtonMetro7.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonMetro7.setColorHover(new java.awt.Color(0, 66, 109));
        rSButtonMetro7.setColorNormal(new java.awt.Color(0, 102, 153));
        rSButtonMetro7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro7.setIconTextGap(20);
        Painel_Menu.add(rSButtonMetro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 250, 50));

        rSButtonMetro8.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonMetro8.setColorHover(new java.awt.Color(0, 66, 109));
        rSButtonMetro8.setColorNormal(new java.awt.Color(0, 102, 153));
        rSButtonMetro8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro8.setIconTextGap(20);
        Painel_Menu.add(rSButtonMetro8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, 50));

        rSButtonMetro9.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonMetro9.setColorHover(new java.awt.Color(0, 66, 109));
        rSButtonMetro9.setColorNormal(new java.awt.Color(0, 102, 153));
        rSButtonMetro9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro9.setIconTextGap(20);
        Painel_Menu.add(rSButtonMetro9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 250, 50));

        rSButtonMetro10.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonMetro10.setColorHover(new java.awt.Color(0, 66, 109));
        rSButtonMetro10.setColorNormal(new java.awt.Color(0, 102, 153));
        rSButtonMetro10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro10.setIconTextGap(20);
        Painel_Menu.add(rSButtonMetro10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 250, 50));

        rSButtonMetro11.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonMetro11.setColorHover(new java.awt.Color(0, 66, 109));
        rSButtonMetro11.setColorNormal(new java.awt.Color(0, 102, 153));
        rSButtonMetro11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro11.setIconTextGap(20);
        Painel_Menu.add(rSButtonMetro11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 250, 50));

        rSButtonMetro12.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonMetro12.setColorHover(new java.awt.Color(0, 66, 109));
        rSButtonMetro12.setColorNormal(new java.awt.Color(0, 102, 153));
        rSButtonMetro12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro12.setIconTextGap(20);
        Painel_Menu.add(rSButtonMetro12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Painel_Opções, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Painel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Painel_Opções4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Painel_desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Painel_Opções, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Painel_Opções4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Painel_desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Painel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed
        // TODO add your handling code here:
        Informações_Usuário user = new Informações_Usuário();
        user.setVisible(true); 
    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        // TODO add your handling code here:
        int logout = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja fazer Logout?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (logout == JOptionPane.YES_OPTION) {
            Tela_Login login = new Tela_Login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed
        // TODO add your handling code here:
        int posição = this.Painel_Menu.getX();
        if (posição > -1) {
            Animacion.Animacion.mover_izquierda(0, -250, 2, 2, Painel_Menu);
        } else {
            Animacion.Animacion.mover_derecha(-250, 0, 2, 2, Painel_Menu);
        }
    }//GEN-LAST:event_btn_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_Menu;
    private javax.swing.JPanel Painel_Opções;
    private javax.swing.JPanel Painel_Opções4;
    public static javax.swing.JPanel Painel_desktop;
    private javax.swing.JButton btn_Menu;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lbl_Usuário;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    private rsbuttom.RSButtonMetro rSButtonMetro10;
    private rsbuttom.RSButtonMetro rSButtonMetro11;
    private rsbuttom.RSButtonMetro rSButtonMetro12;
    public static rsbuttom.RSButtonMetro rSButtonMetro2;
    private rsbuttom.RSButtonMetro rSButtonMetro4;
    private rsbuttom.RSButtonMetro rSButtonMetro5;
    private rsbuttom.RSButtonMetro rSButtonMetro6;
    private rsbuttom.RSButtonMetro rSButtonMetro7;
    private rsbuttom.RSButtonMetro rSButtonMetro8;
    private rsbuttom.RSButtonMetro rSButtonMetro9;
    // End of variables declaration//GEN-END:variables
}
