/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lineup.view;

import br.com.lineup.controller.ControllerCliente;
import br.com.lineup.controller.ControllerOrdem_de_Serviço;
import br.com.lineup.model.ModelCliente;
import br.com.lineup.model.ModelOrdem_de_Serviço;
import static br.com.lineup.view.MENU.Painel_Desktop;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siqueira
 */
public class Tela_Home extends javax.swing.JPanel {

    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelClientes = new ArrayList<>();

    ControllerOrdem_de_Serviço controllerOrdem_de_Serviço = new ControllerOrdem_de_Serviço();
    ModelOrdem_de_Serviço modelOrdem_de_Serviço = new ModelOrdem_de_Serviço();
    ArrayList<ModelOrdem_de_Serviço> listaModelOS = new ArrayList<>();

    /**
     * Creates new form Tela_Funcinários
     */
    public Tela_Home() {
        initComponents();
        Busca_OS();
    }

    private void Busca_OS() {
        listaModelOS = controllerOrdem_de_Serviço.getListaOrdem_de_ServiçoController();
        DefaultTableModel tabela = (DefaultTableModel) Tela_Home.tabelaOS.getModel();
        tabela.setNumRows(0);

        int tam_lista = listaModelOS.size();
        for (int i = 0; i < tam_lista; i++) {
            tabela.addRow(new Object[]{
                listaModelOS.get(i).getOs(),
                listaModelOS.get(i).getDataos(),
                listaModelOS.get(i).getStatusOS(),
                listaModelOS.get(i).getAparelho(),
                listaModelOS.get(i).getDefeito(),
                listaModelOS.get(i).getServico(),
                listaModelOS.get(i).getTecnico(),
                listaModelOS.get(i).getValorservico(),
                listaModelOS.get(i).getId_cli(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSButtonPane3 = new rojerusan.RSButtonPane();
        jLabel21 = new javax.swing.JLabel();
        lbl_Usuário2 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        rSButtonPane7 = new rojerusan.RSButtonPane();
        jLabel31 = new javax.swing.JLabel();
        lbl_Prod_Est3 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        rSButtonPane4 = new rojerusan.RSButtonPane();
        jLabel22 = new javax.swing.JLabel();
        lbl_Usuário4 = new javax.swing.JLabel();
        lbl_clientes = new javax.swing.JLabel();
        rSButtonPane5 = new rojerusan.RSButtonPane();
        jLabel20 = new javax.swing.JLabel();
        lbl_Usuário5 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaOS = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 648));

        rSButtonPane3.setBackground(new java.awt.Color(255, 102, 102));
        rSButtonPane3.setColorHover(new java.awt.Color(0, 66, 109));
        rSButtonPane3.setColorNormal(new java.awt.Color(255, 102, 102));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons50px/Vendas_50px.png"))); // NOI18N

        lbl_Usuário2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_Usuário2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Usuário2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Usuário2.setText("Vendas Efetuadas");
        lbl_Usuário2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("0");

        javax.swing.GroupLayout rSButtonPane3Layout = new javax.swing.GroupLayout(rSButtonPane3);
        rSButtonPane3.setLayout(rSButtonPane3Layout);
        rSButtonPane3Layout.setHorizontalGroup(
            rSButtonPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSButtonPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addContainerGap())
            .addComponent(lbl_Usuário2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );
        rSButtonPane3Layout.setVerticalGroup(
            rSButtonPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSButtonPane3Layout.createSequentialGroup()
                .addGroup(rSButtonPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Usuário2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rSButtonPane7.setBackground(new java.awt.Color(0, 153, 0));
        rSButtonPane7.setColorHover(new java.awt.Color(0, 66, 109));
        rSButtonPane7.setColorNormal(new java.awt.Color(0, 153, 0));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons50px/Produto_50px.png"))); // NOI18N

        lbl_Prod_Est3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_Prod_Est3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Prod_Est3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Prod_Est3.setText("Produtos em Estoque");
        lbl_Prod_Est3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Prod_Est3.setIconTextGap(0);

        jLabel32.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("0");

        javax.swing.GroupLayout rSButtonPane7Layout = new javax.swing.GroupLayout(rSButtonPane7);
        rSButtonPane7.setLayout(rSButtonPane7Layout);
        rSButtonPane7Layout.setHorizontalGroup(
            rSButtonPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSButtonPane7Layout.createSequentialGroup()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addContainerGap())
            .addComponent(lbl_Prod_Est3, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );
        rSButtonPane7Layout.setVerticalGroup(
            rSButtonPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSButtonPane7Layout.createSequentialGroup()
                .addGroup(rSButtonPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Prod_Est3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rSButtonPane4.setBackground(new java.awt.Color(255, 153, 102));
        rSButtonPane4.setColorHover(new java.awt.Color(0, 66, 109));
        rSButtonPane4.setColorNormal(new java.awt.Color(255, 153, 102));
        rSButtonPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonPane4rSButtonPane3MouseClicked(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons50px/Cliente_50px.png"))); // NOI18N

        lbl_Usuário4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_Usuário4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Usuário4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Usuário4.setText("Clientes Cadastrados");
        lbl_Usuário4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_clientes.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbl_clientes.setForeground(new java.awt.Color(255, 255, 255));
        lbl_clientes.setText("0");

        javax.swing.GroupLayout rSButtonPane4Layout = new javax.swing.GroupLayout(rSButtonPane4);
        rSButtonPane4.setLayout(rSButtonPane4Layout);
        rSButtonPane4Layout.setHorizontalGroup(
            rSButtonPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSButtonPane4Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_clientes)
                .addContainerGap())
            .addComponent(lbl_Usuário4, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );
        rSButtonPane4Layout.setVerticalGroup(
            rSButtonPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSButtonPane4Layout.createSequentialGroup()
                .addGroup(rSButtonPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(lbl_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Usuário4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rSButtonPane5.setBackground(new java.awt.Color(102, 153, 255));
        rSButtonPane5.setColorHover(new java.awt.Color(0, 66, 109));
        rSButtonPane5.setColorNormal(new java.awt.Color(102, 153, 255));
        rSButtonPane5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonPane5MouseClicked(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons50px/OS_50px.png"))); // NOI18N

        lbl_Usuário5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_Usuário5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Usuário5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Usuário5.setText("Ordens de Serviço");
        lbl_Usuário5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("0");

        javax.swing.GroupLayout rSButtonPane5Layout = new javax.swing.GroupLayout(rSButtonPane5);
        rSButtonPane5.setLayout(rSButtonPane5Layout);
        rSButtonPane5Layout.setHorizontalGroup(
            rSButtonPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSButtonPane5Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addContainerGap())
            .addComponent(lbl_Usuário5, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );
        rSButtonPane5Layout.setVerticalGroup(
            rSButtonPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSButtonPane5Layout.createSequentialGroup()
                .addGroup(rSButtonPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Usuário5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 66, 109));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Ordens de Serviço abertas:");

        tabelaOS.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tabelaOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº OS", "Data OS", "Status", "Aparelho", "Defeito", "Serviço", "Técnico", "Valor do Serviço", "Cód. Cliente", "Nome do Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaOS.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaOS.setFocusable(false);
        tabelaOS.setGridColor(new java.awt.Color(0, 0, 0));
        tabelaOS.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaOS.setRowHeight(25);
        tabelaOS.setShowVerticalLines(false);
        tabelaOS.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelaOS);
        if (tabelaOS.getColumnModel().getColumnCount() > 0) {
            tabelaOS.getColumnModel().getColumn(0).setResizable(false);
            tabelaOS.getColumnModel().getColumn(0).setPreferredWidth(120);
            tabelaOS.getColumnModel().getColumn(1).setResizable(false);
            tabelaOS.getColumnModel().getColumn(1).setPreferredWidth(150);
            tabelaOS.getColumnModel().getColumn(2).setResizable(false);
            tabelaOS.getColumnModel().getColumn(2).setPreferredWidth(200);
            tabelaOS.getColumnModel().getColumn(3).setResizable(false);
            tabelaOS.getColumnModel().getColumn(3).setPreferredWidth(200);
            tabelaOS.getColumnModel().getColumn(4).setResizable(false);
            tabelaOS.getColumnModel().getColumn(4).setPreferredWidth(200);
            tabelaOS.getColumnModel().getColumn(5).setResizable(false);
            tabelaOS.getColumnModel().getColumn(5).setPreferredWidth(170);
            tabelaOS.getColumnModel().getColumn(6).setResizable(false);
            tabelaOS.getColumnModel().getColumn(6).setPreferredWidth(170);
            tabelaOS.getColumnModel().getColumn(7).setResizable(false);
            tabelaOS.getColumnModel().getColumn(7).setPreferredWidth(100);
            tabelaOS.getColumnModel().getColumn(8).setResizable(false);
            tabelaOS.getColumnModel().getColumn(8).setPreferredWidth(120);
            tabelaOS.getColumnModel().getColumn(9).setResizable(false);
            tabelaOS.getColumnModel().getColumn(9).setPreferredWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rSButtonPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rSButtonPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rSButtonPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rSButtonPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(10, 10, 10)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rSButtonPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonPane4rSButtonPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonPane4rSButtonPane3MouseClicked
        // TODO add your handling code here:
        new Trocar_Painel(Painel_Desktop, new Tela_Cliente()); 
    }//GEN-LAST:event_rSButtonPane4rSButtonPane3MouseClicked

    private void rSButtonPane5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonPane5MouseClicked
        // TODO add your handling code here:
        new Trocar_Painel(Painel_Desktop, new Tela_OS());
    }//GEN-LAST:event_rSButtonPane5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public static javax.swing.JLabel lbl_Prod_Est3;
    public static javax.swing.JLabel lbl_Usuário2;
    public static javax.swing.JLabel lbl_Usuário4;
    public static javax.swing.JLabel lbl_Usuário5;
    private javax.swing.JLabel lbl_clientes;
    private rojerusan.RSButtonPane rSButtonPane3;
    private rojerusan.RSButtonPane rSButtonPane4;
    private rojerusan.RSButtonPane rSButtonPane5;
    private rojerusan.RSButtonPane rSButtonPane7;
    public static javax.swing.JTable tabelaOS;
    // End of variables declaration//GEN-END:variables
}
