/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lineup.view;

import br.com.lineup.controller.ControllerCliente;
import br.com.lineup.model.ModelCliente;
import static br.com.lineup.view.MENU.Painel_Desktop;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siqueira
 */
public class Tela_Cliente extends javax.swing.JPanel {

    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelClientes = new ArrayList<>();

    /**
     * Creates new form Tela_Cliente
     */
    public Tela_Cliente() {
        initComponents();

        busca_cliente();
    }

    // Chamar o método de busca de clientes da tabela:
    private void busca_cliente() {
        listaModelClientes = controllerCliente.getListaClienteController();
        DefaultTableModel tabela = (DefaultTableModel) tabelacliente.getModel();
        tabela.setNumRows(0);

        int tam_lista = listaModelClientes.size();
        for (int i = 0; i < tam_lista; i++) {
            tabela.addRow(new Object[]{
                listaModelClientes.get(i).getId_cli(),
                listaModelClientes.get(i).getNome_cli(),
                listaModelClientes.get(i).getFone_cli(),
                listaModelClientes.get(i).getCelular_cli(),
                listaModelClientes.get(i).getEmail_cli(),
                listaModelClientes.get(i).getEnd_cli(),
                listaModelClientes.get(i).getComplemento(),
                listaModelClientes.get(i).getBairro(),
                listaModelClientes.get(i).getCidade(),
                listaModelClientes.get(i).getEstado(),
                listaModelClientes.get(i).getRG_cli(),
                listaModelClientes.get(i).getCpf_cli(),});

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSButtonMetro4 = new rsbuttom.RSButtonMetro();
        btn_Cadastrar = new rojerusan.RSButtonMetro();
        btn_Atualizar = new rojerusan.RSButtonMetro();
        btn_Apagar = new rojerusan.RSButtonMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelacliente = new javax.swing.JTable();
        txtclienteid = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtclienteendereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtclienteemail = new javax.swing.JTextField();
        txtclientecelular = new javax.swing.JFormattedTextField();
        txtclienterg = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtclientenome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtclientecomplemento = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtclientebairro = new javax.swing.JTextField();
        txtclientecidade = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtclientebusca = new javax.swing.JTextField();
        rSButtonMetro1 = new rojerusan.RSButtonMetro();
        jLabel6 = new javax.swing.JLabel();
        txtclientefone = new javax.swing.JFormattedTextField();
        txtclientecpf = new javax.swing.JFormattedTextField();
        jSeparator3 = new javax.swing.JSeparator();
        comboclienteestado = new javax.swing.JComboBox<>();

        jFormattedTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jFormattedTextField4.setForeground(new java.awt.Color(0, 102, 153));
        try {
            jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 610));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gerenciar Clientes");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons50px/Cliente_50px.png"))); // NOI18N

        rSButtonMetro4.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonMetro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Close.png"))); // NOI18N
        rSButtonMetro4.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetro4.setColorNormal(new java.awt.Color(0, 102, 153));
        rSButtonMetro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButtonMetro4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(rSButtonMetro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btn_Cadastrar.setBackground(new java.awt.Color(0, 204, 102));
        btn_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Adicionar_32px.png"))); // NOI18N
        btn_Cadastrar.setText("Cadastrar");
        btn_Cadastrar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });

        btn_Atualizar.setBackground(new java.awt.Color(0, 153, 204));
        btn_Atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Atualizar_32px.png"))); // NOI18N
        btn_Atualizar.setText("Atualizar");
        btn_Atualizar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });

        btn_Apagar.setBackground(new java.awt.Color(255, 0, 0));
        btn_Apagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Deletar_32px.png"))); // NOI18N
        btn_Apagar.setText("Apagar");
        btn_Apagar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ApagarActionPerformed(evt);
            }
        });

        tabelacliente.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tabelacliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Telefone", "Celular", "Email", "Endereço", "Complemento", "Bairro", "Cidade", "Estado", "RG", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelacliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelacliente.setRowHeight(25);
        tabelacliente.getTableHeader().setReorderingAllowed(false);
        tabelacliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaclienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelacliente);
        if (tabelacliente.getColumnModel().getColumnCount() > 0) {
            tabelacliente.getColumnModel().getColumn(0).setResizable(false);
            tabelacliente.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabelacliente.getColumnModel().getColumn(1).setResizable(false);
            tabelacliente.getColumnModel().getColumn(1).setPreferredWidth(250);
            tabelacliente.getColumnModel().getColumn(2).setResizable(false);
            tabelacliente.getColumnModel().getColumn(2).setPreferredWidth(150);
            tabelacliente.getColumnModel().getColumn(3).setResizable(false);
            tabelacliente.getColumnModel().getColumn(3).setPreferredWidth(150);
            tabelacliente.getColumnModel().getColumn(4).setResizable(false);
            tabelacliente.getColumnModel().getColumn(4).setPreferredWidth(200);
            tabelacliente.getColumnModel().getColumn(5).setResizable(false);
            tabelacliente.getColumnModel().getColumn(5).setPreferredWidth(250);
            tabelacliente.getColumnModel().getColumn(6).setResizable(false);
            tabelacliente.getColumnModel().getColumn(6).setPreferredWidth(150);
            tabelacliente.getColumnModel().getColumn(7).setResizable(false);
            tabelacliente.getColumnModel().getColumn(7).setPreferredWidth(150);
            tabelacliente.getColumnModel().getColumn(8).setResizable(false);
            tabelacliente.getColumnModel().getColumn(8).setPreferredWidth(150);
            tabelacliente.getColumnModel().getColumn(9).setResizable(false);
            tabelacliente.getColumnModel().getColumn(9).setPreferredWidth(100);
            tabelacliente.getColumnModel().getColumn(10).setResizable(false);
            tabelacliente.getColumnModel().getColumn(10).setPreferredWidth(100);
            tabelacliente.getColumnModel().getColumn(11).setResizable(false);
            tabelacliente.getColumnModel().getColumn(11).setPreferredWidth(150);
        }

        txtclienteid.setEditable(false);
        txtclienteid.setBackground(new java.awt.Color(255, 255, 255));
        txtclienteid.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtclienteid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtclienteid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel20.setBackground(new java.awt.Color(0, 66, 109));
        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 153));
        jLabel20.setText("Endereço:");

        txtclienteendereco.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtclienteendereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtclienteendereco.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel5.setBackground(new java.awt.Color(0, 66, 109));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("*Código:");

        jLabel7.setBackground(new java.awt.Color(0, 66, 109));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("Celular:");

        txtclienteemail.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtclienteemail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtclienteemail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtclientecelular.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        try {
            txtclientecelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtclientecelular.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        txtclienterg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        try {
            txtclienterg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtclienterg.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel9.setBackground(new java.awt.Color(0, 66, 109));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("*Nome:");

        jLabel10.setBackground(new java.awt.Color(0, 66, 109));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("*Telefone:");

        txtclientenome.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtclientenome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtclientenome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel8.setBackground(new java.awt.Color(0, 66, 109));
        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("Email:");

        jSeparator2.setBackground(new java.awt.Color(0, 102, 153));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 153));

        txtclientecomplemento.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtclientecomplemento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtclientecomplemento.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel21.setBackground(new java.awt.Color(0, 66, 109));
        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 153));
        jLabel21.setText("Complemento:");

        jLabel22.setBackground(new java.awt.Color(0, 66, 109));
        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 153));
        jLabel22.setText("Bairro:");

        txtclientebairro.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtclientebairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtclientebairro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtclientecidade.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtclientecidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtclientecidade.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel23.setBackground(new java.awt.Color(0, 66, 109));
        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 153));
        jLabel23.setText("Cidade:");

        jLabel24.setBackground(new java.awt.Color(0, 66, 109));
        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 153));
        jLabel24.setText("*RG:");

        jLabel25.setBackground(new java.awt.Color(0, 66, 109));
        jLabel25.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 153));
        jLabel25.setText("*CPF:");

        jLabel11.setBackground(new java.awt.Color(0, 66, 109));
        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 153));
        jLabel11.setText("Pesquisar Cliente:");

        txtclientebusca.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtclientebusca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtclientebusca.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        rSButtonMetro1.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Busca_24px.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(0, 66, 109));
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("*Estado:");

        txtclientefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        try {
            txtclientefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtclientefone.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        txtclientecpf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        try {
            txtclientecpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtclientecpf.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jSeparator3.setBackground(new java.awt.Color(0, 102, 153));
        jSeparator3.setForeground(new java.awt.Color(0, 102, 153));

        comboclienteestado.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        comboclienteestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        comboclienteestado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        comboclienteestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboclienteestadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_Apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(48, 48, 48)
                        .addComponent(txtclientebusca, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator2))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtclientecomplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addGap(14, 14, 14))
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtclientebairro, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(209, 209, 209)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(162, 162, 162))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtclientecidade)
                                .addGap(10, 10, 10))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(161, 161, 161))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtclientecelular)
                                .addGap(21, 21, 21)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(180, 180, 180))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtclienteemail)
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtclienteendereco)
                                .addGap(13, 13, 13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(210, 210, 210))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtclienteid)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(156, 156, 156)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(251, 251, 251))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtclientenome)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtclientefone)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(130, 130, 130))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(118, 118, 118))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboclienteestado, 0, 165, Short.MAX_VALUE)
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(118, 118, 118))
                            .addComponent(txtclienterg, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(320, 320, 320))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtclientecpf, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(206, 206, 206))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtclientebusca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel9))
                    .addComponent(jLabel10))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtclienteid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtclientenome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtclientefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel20))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtclientecelular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtclienteendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtclienteemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtclientecomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtclientebairro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtclientecidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel24))
                    .addComponent(jLabel25))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboclienteestado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtclienterg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtclientecpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
        //Adicionar dados do cliente ao banco de dados:
        modelCliente.setFone_cli(this.txtclientefone.getText());
        modelCliente.setNome_cli(this.txtclientenome.getText());
        modelCliente.setCelular_cli(this.txtclientecelular.getText());
        modelCliente.setEmail_cli(this.txtclienteemail.getText());
        modelCliente.setEnd_cli(this.txtclienteendereco.getText());
        modelCliente.setComplemento(this.txtclientecomplemento.getText());
        modelCliente.setBairro(this.txtclientebairro.getText());
        modelCliente.setCidade(this.txtclientecidade.getText());
        modelCliente.setEstado(this.comboclienteestado.getSelectedItem().toString());
        modelCliente.setRG_cli(this.txtclienterg.getText());
        modelCliente.setCpf_cli(this.txtclientecpf.getText());

        //Condição para testar se houve sucesso ou erro no cadastro:
        if (controllerCliente.salvarClienteController(modelCliente) > 0) {
            JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar cliente!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

        // Setar campos como nulo:
        txtclientebusca.setText(null);
        txtclientecpf.setText(null);
        txtclienteemail.setText(null);
        txtclienteendereco.setText(null);
        txtclientefone.setText(null);
        txtclienteid.setText(null);
        txtclientenome.setText(null);
        txtclientebairro.setText(null);
        txtclientecelular.setText(null);
        txtclientecomplemento.setText(null);
        txtclienterg.setText(null);
        comboclienteestado.setSelectedItem(null);
        txtclientecidade.setText(null);

        // Chamar o método de busca de clientes da tabela:
        busca_cliente();
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void comboclienteestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboclienteestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboclienteestadoActionPerformed

    private void rSButtonMetro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro4ActionPerformed
        // TODO add your handling code here:
        new Trocar_Painel(Painel_Desktop, new Tela_Home());
    }//GEN-LAST:event_rSButtonMetro4ActionPerformed

    private void tabelaclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaclienteMouseClicked
// Setar campos como nulo:
        txtclientebusca.setText(null);
        txtclientecpf.setText(null);
        txtclienteemail.setText(null);
        txtclienteendereco.setText(null);
        txtclientefone.setText(null);
        txtclienteid.setText(null);
        txtclientenome.setText(null);
        txtclientebairro.setText(null);
        txtclientecelular.setText(null);
        txtclientecomplemento.setText(null);
        txtclienterg.setText(null);
        comboclienteestado.setSelectedItem(null);
        txtclientecidade.setText(null);

        // Setar dados da tabela(JTable) para os campos de texto:
        int set = tabelacliente.getSelectedRow();
        txtclienteid.setText(tabelacliente.getModel().getValueAt(set, 0).toString());
        txtclientenome.setText(tabelacliente.getModel().getValueAt(set, 1).toString());
        txtclientefone.setText(tabelacliente.getModel().getValueAt(set, 2).toString());
        txtclientecelular.setText(tabelacliente.getModel().getValueAt(set, 3).toString());
        txtclienteemail.setText(tabelacliente.getModel().getValueAt(set, 4).toString());
        txtclienteendereco.setText(tabelacliente.getModel().getValueAt(set, 5).toString());
        txtclientecomplemento.setText(tabelacliente.getModel().getValueAt(set, 6).toString());
        txtclientebairro.setText(tabelacliente.getModel().getValueAt(set, 7).toString());
        txtclientecidade.setText(tabelacliente.getModel().getValueAt(set, 8).toString());
        comboclienteestado.setSelectedItem(tabelacliente.getModel().getValueAt(set, 9).toString());
        txtclienterg.setText(tabelacliente.getModel().getValueAt(set, 10).toString());
        txtclientecpf.setText(tabelacliente.getModel().getValueAt(set, 11).toString());

        // Setar o botão cadastrar como desabilitado, para não poder cadastrar outra pessoa com a mesma ID:
        btn_Cadastrar.setEnabled(false);
    }//GEN-LAST:event_tabelaclienteMouseClicked

    private void btn_ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ApagarActionPerformed
        // Apagar dados do cliente a partir do ID:
        int del = tabelacliente.getSelectedRow();
        int id_cli = (int) tabelacliente.getValueAt(del, 0);
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja deletar este Cliente?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            //Condição para testar se houve sucesso ou erro na exclusão:
            try {
                if (controllerCliente.excluirClienteController(id_cli)) {
                    JOptionPane.showMessageDialog(this, "Cliente deletado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao tentar deletar cliente!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Este cliente não pode ser deletado, pois já está vinculado a uma Ordem de Serviço!");
            }
        }
        // Setar campos como nulo:
        txtclientebusca.setText(null);
        txtclientecpf.setText(null);
        txtclienteemail.setText(null);
        txtclienteendereco.setText(null);
        txtclientefone.setText(null);
        txtclienteid.setText(null);
        txtclientenome.setText(null);
        txtclientebairro.setText(null);
        txtclientecelular.setText(null);
        txtclientecomplemento.setText(null);
        txtclienterg.setText(null);
        comboclienteestado.setSelectedItem(null);
        txtclientecidade.setText(null);

        // Chamar o método de busca de clientes da tabela:
        busca_cliente();

        btn_Cadastrar.setEnabled(true);
    }//GEN-LAST:event_btn_ApagarActionPerformed

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        // Aletar dados do cliente:

    }//GEN-LAST:event_btn_AtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btn_Apagar;
    private rojerusan.RSButtonMetro btn_Atualizar;
    private rojerusan.RSButtonMetro btn_Cadastrar;
    private javax.swing.JComboBox<String> comboclienteestado;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private rojerusan.RSButtonMetro rSButtonMetro1;
    private rsbuttom.RSButtonMetro rSButtonMetro4;
    private javax.swing.JTable tabelacliente;
    private javax.swing.JTextField txtclientebairro;
    private javax.swing.JTextField txtclientebusca;
    private javax.swing.JFormattedTextField txtclientecelular;
    private javax.swing.JTextField txtclientecidade;
    private javax.swing.JTextField txtclientecomplemento;
    private javax.swing.JFormattedTextField txtclientecpf;
    private javax.swing.JTextField txtclienteemail;
    private javax.swing.JTextField txtclienteendereco;
    private javax.swing.JFormattedTextField txtclientefone;
    private javax.swing.JTextField txtclienteid;
    private javax.swing.JTextField txtclientenome;
    private javax.swing.JFormattedTextField txtclienterg;
    // End of variables declaration//GEN-END:variables
}
