package br.com.lineup.view;

import br.com.lineup.controller.ControllerCliente;
import br.com.lineup.controller.ControllerOrdem_de_Serviço;
import br.com.lineup.controller.ControllerServiços;
import br.com.lineup.controller.ControllerUsuário;
import br.com.lineup.model.ModelCliente;
import br.com.lineup.model.ModelOrdem_de_Serviço;
import br.com.lineup.model.ModelServiços;
import br.com.lineup.model.ModelUsuário;
import static br.com.lineup.view.MENU.Painel_Desktop;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siqueira
 */
public class Tela_OS extends javax.swing.JPanel {

    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelClientes = new ArrayList<>();

    ControllerOrdem_de_Serviço controllerOrdem_de_Serviço = new ControllerOrdem_de_Serviço();
    ModelOrdem_de_Serviço modelOrdem_de_Serviço = new ModelOrdem_de_Serviço();
    ArrayList<ModelOrdem_de_Serviço> listaModelOrdem_de_Serviços = new ArrayList<>();

    ControllerServiços controllerServiços = new ControllerServiços();
    ModelServiços modelServiços = new ModelServiços();
    ArrayList<ModelServiços> listaModelServiços = new ArrayList<>();

    ControllerUsuário controllerUsuário = new ControllerUsuário();
    ModelUsuário modelUsuário = new ModelUsuário();
    ArrayList<ModelUsuário> listamodelUsuário_Técnico = new ArrayList<>();

    /**,-
     * Creates new form Tela_OS
     */
    public Tela_OS() {
        initComponents();

        Combo_Cliente();
        Popular_Cliente();
        Combo_Serviço();
        Popular_Serviço();
        Combo_Técnico();

        combo_StatusOs.setSelectedItem(null);
        combo_Técnico.setSelectedItem(null);
//        combo_Cliente.setSelectedItem(null);
//        combo_Serviço.setSelectedItem(null);
    }

    private void Busca_OS() {
        listaModelOrdem_de_Serviços = controllerOrdem_de_Serviço.getListaOrdem_de_ServiçoController();
        DefaultTableModel tabela = (DefaultTableModel) tabelaOS.getModel();
        tabela.setNumRows(0);

        int tam_lista = listaModelOrdem_de_Serviços.size();
        for (int i = 0; i < tam_lista; i++) {
            tabela.addRow(new Object[]{
                listaModelOrdem_de_Serviços.get(i).getOs(),
                listaModelOrdem_de_Serviços.get(i).getDataos(),
                listaModelOrdem_de_Serviços.get(i).getStatusOS(),
                listaModelOrdem_de_Serviços.get(i).getAparelho(),
                listaModelOrdem_de_Serviços.get(i).getDefeito(),
                listaModelOrdem_de_Serviços.get(i).getServico(),
                listaModelOrdem_de_Serviços.get(i).getValorservico(),
                listaModelOrdem_de_Serviços.get(i).getTecnico(),
                listaModelOrdem_de_Serviços.get(i).getId_cli(),});
        }
    }

    private void Combo_Cliente() {
        listaModelClientes = controllerCliente.getListaClienteController();
        combo_Cliente.removeAllItems();
        for (int i = 0; i < listaModelClientes.size(); i++) {
            combo_Cliente.addItem(listaModelClientes.get(i).getNome_cli());
        }
    }

    private void Combo_Serviço() {
        listaModelServiços = controllerServiços.getListaServiçosController();
        combo_Serviço.removeAllItems();

        for (int i = 0; i < listaModelServiços.size(); i++) {
            combo_Serviço.addItem(listaModelServiços.get(i).getDescricao_servico());
        }
    }

    private void Combo_Técnico() {
        listamodelUsuário_Técnico = controllerUsuário.getListaTécnicoController();
        combo_Técnico.removeAllItems();

        for (int i = 0; i < listamodelUsuário_Técnico.size(); i++) {
            combo_Técnico.addItem(listamodelUsuário_Técnico.get(i).getNomeuser());
        }
    }

    private void Popular_Serviço() {
        if (combo_Serviço.isPopupVisible()) {
            modelServiços = controllerServiços.getServiçosController(combo_Serviço.getSelectedItem().toString());
        }
        txt_ValorServiço.setText(String.valueOf(modelServiços.getValor_servico()));
    }

    private void Popular_Cliente() {
        if (combo_Cliente.isPopupVisible()) {
            modelCliente = controllerCliente.getClienteController(combo_Cliente.getSelectedItem().toString());
        }
        txt_IdCli.setText(String.valueOf(modelCliente.getId_cli()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        jLabel5 = new javax.swing.JLabel();
        txt_IdCli = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combo_Cliente = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_OS = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_DataOs = new javax.swing.JTextField();
        combo_StatusOs = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txt_Aparelho = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_Defeito = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        combo_Serviço = new javax.swing.JComboBox<>();
        btn_add_Serviço = new rojerusan.RSButtonMetro();
        jLabel16 = new javax.swing.JLabel();
        combo_Técnico = new javax.swing.JComboBox<>();
        btn_Add_Cliente = new rojerusan.RSButtonMetro();
        jLabel18 = new javax.swing.JLabel();
        txt_ValorServiço = new javax.swing.JTextField();
        btn_Imprimir = new rojerusan.RSButtonMetro();
        btn_Atualizar = new rojerusan.RSButtonMetro();
        btn_Apagar = new rojerusan.RSButtonMetro();
        btn_Cadastrar = new rojerusan.RSButtonMetro();
        btn_Pesquisar = new rojerusan.RSButtonMetro();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaOS = new javax.swing.JTable();
        btn_Add_Técnico = new rojerusan.RSButtonMetro();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(0, 102, 153));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gerenciar Ordem de Serviço");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons50px/OS_50px.png"))); // NOI18N

        rSButtonMetro1.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Close.png"))); // NOI18N
        rSButtonMetro1.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetro1.setColorNormal(new java.awt.Color(0, 102, 153));
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel5.setBackground(new java.awt.Color(0, 66, 109));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Cód. Cliente:");

        txt_IdCli.setEditable(false);
        txt_IdCli.setBackground(new java.awt.Color(255, 255, 255));
        txt_IdCli.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_IdCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_IdCli.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_IdCli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_IdCliFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_IdCliFocusLost(evt);
            }
        });
        txt_IdCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_IdCliKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_IdCliKeyReleased(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 66, 109));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("Nome do Cliente:");

        jLabel6.setBackground(new java.awt.Color(0, 66, 109));
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("Status da OS:");

        combo_Cliente.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        combo_Cliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_ClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        combo_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_ClienteActionPerformed(evt);
            }
        });
        combo_Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                combo_ClienteKeyReleased(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 66, 109));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("Nº OS:");

        txt_OS.setEditable(false);
        txt_OS.setBackground(new java.awt.Color(255, 255, 255));
        txt_OS.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_OS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_OS.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel11.setBackground(new java.awt.Color(0, 66, 109));
        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 153));
        jLabel11.setText("Data de Emissão:");

        txt_DataOs.setEditable(false);
        txt_DataOs.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_DataOs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_DataOs.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        combo_StatusOs.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        combo_StatusOs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Aguardando Aprovação", "Aguardando Pagamento", "Finalizada", "Entregue" }));
        combo_StatusOs.setBorder(null);
        combo_StatusOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_StatusOsActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 66, 109));
        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 153));
        jLabel12.setText("Aparelho:");

        txt_Aparelho.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Aparelho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Aparelho.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel13.setBackground(new java.awt.Color(0, 66, 109));
        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 153));
        jLabel13.setText("Defeito:");

        txt_Defeito.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Defeito.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Defeito.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel15.setBackground(new java.awt.Color(0, 66, 109));
        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 153));
        jLabel15.setText("Serviço Prestado:");

        combo_Serviço.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        combo_Serviço.setMaximumRowCount(5);
        combo_Serviço.setBorder(null);
        combo_Serviço.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
                combo_ServiçoPopupMenuCanceled(evt);
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_ServiçoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                combo_ServiçoPopupMenuWillBecomeVisible(evt);
            }
        });
        combo_Serviço.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                combo_ServiçoKeyReleased(evt);
            }
        });

        btn_add_Serviço.setBackground(new java.awt.Color(255, 255, 255));
        btn_add_Serviço.setForeground(new java.awt.Color(0, 66, 109));
        btn_add_Serviço.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Add_24px.png"))); // NOI18N
        btn_add_Serviço.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        btn_add_Serviço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_ServiçoActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(0, 66, 109));
        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 153));
        jLabel16.setText("Técnico:");

        combo_Técnico.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        combo_Técnico.setMaximumRowCount(5);
        combo_Técnico.setBorder(null);

        btn_Add_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        btn_Add_Cliente.setForeground(new java.awt.Color(0, 66, 109));
        btn_Add_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Add_24px.png"))); // NOI18N
        btn_Add_Cliente.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        btn_Add_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add_ClienteActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(0, 66, 109));
        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 153));
        jLabel18.setText("Valor do Serviço:");

        txt_ValorServiço.setEditable(false);
        txt_ValorServiço.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_ValorServiço.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_ValorServiço.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btn_Imprimir.setBackground(new java.awt.Color(153, 153, 255));
        btn_Imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Imprimir_32px.png"))); // NOI18N
        btn_Imprimir.setText("Imprimir");
        btn_Imprimir.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImprimirActionPerformed(evt);
            }
        });

        btn_Atualizar.setBackground(new java.awt.Color(0, 153, 204));
        btn_Atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Alterar_32px.png"))); // NOI18N
        btn_Atualizar.setText("Atualizar");
        btn_Atualizar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });

        btn_Apagar.setBackground(new java.awt.Color(255, 0, 0));
        btn_Apagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Apagar_32px.png"))); // NOI18N
        btn_Apagar.setText("Apagar");
        btn_Apagar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ApagarActionPerformed(evt);
            }
        });

        btn_Cadastrar.setBackground(new java.awt.Color(0, 204, 102));
        btn_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Add_32px.png"))); // NOI18N
        btn_Cadastrar.setText("Cadastrar");
        btn_Cadastrar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });

        btn_Pesquisar.setBackground(new java.awt.Color(0, 204, 204));
        btn_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Buscar_32px.png"))); // NOI18N
        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });

        tabelaOS.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tabelaOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº OS", "Data OS", "Status", "Aparelho", "Defeito", "Serviço", "Valor do Serviço", "Técnico", "Cód. Cliente", "Nome do Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaOS.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaOS.setFocusable(false);
        tabelaOS.setGridColor(new java.awt.Color(0, 0, 0));
        tabelaOS.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaOS.setRowHeight(25);
        tabelaOS.setShowVerticalLines(false);
        tabelaOS.getTableHeader().setReorderingAllowed(false);
        tabelaOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaOSMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaOS);
        if (tabelaOS.getColumnModel().getColumnCount() > 0) {
            tabelaOS.getColumnModel().getColumn(0).setResizable(false);
            tabelaOS.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabelaOS.getColumnModel().getColumn(1).setResizable(false);
            tabelaOS.getColumnModel().getColumn(1).setPreferredWidth(150);
            tabelaOS.getColumnModel().getColumn(2).setResizable(false);
            tabelaOS.getColumnModel().getColumn(2).setPreferredWidth(150);
            tabelaOS.getColumnModel().getColumn(3).setResizable(false);
            tabelaOS.getColumnModel().getColumn(3).setPreferredWidth(150);
            tabelaOS.getColumnModel().getColumn(4).setResizable(false);
            tabelaOS.getColumnModel().getColumn(4).setPreferredWidth(150);
            tabelaOS.getColumnModel().getColumn(5).setResizable(false);
            tabelaOS.getColumnModel().getColumn(5).setPreferredWidth(150);
            tabelaOS.getColumnModel().getColumn(6).setResizable(false);
            tabelaOS.getColumnModel().getColumn(6).setPreferredWidth(100);
            tabelaOS.getColumnModel().getColumn(7).setResizable(false);
            tabelaOS.getColumnModel().getColumn(7).setPreferredWidth(150);
            tabelaOS.getColumnModel().getColumn(8).setResizable(false);
            tabelaOS.getColumnModel().getColumn(8).setPreferredWidth(100);
            tabelaOS.getColumnModel().getColumn(9).setResizable(false);
            tabelaOS.getColumnModel().getColumn(9).setPreferredWidth(200);
        }

        btn_Add_Técnico.setBackground(new java.awt.Color(255, 255, 255));
        btn_Add_Técnico.setForeground(new java.awt.Color(0, 66, 109));
        btn_Add_Técnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Add_24px.png"))); // NOI18N
        btn_Add_Técnico.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        btn_Add_Técnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add_TécnicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(138, 138, 138)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(170, 170, 170)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(120, 120, 120))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_OS, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_DataOs, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(combo_StatusOs, 0, 230, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(400, 400, 400))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_IdCli, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(combo_Cliente, 0, 500, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(btn_Add_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addGap(280, 280, 280)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addGap(300, 300, 300))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_Aparelho, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_Defeito, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(160, 160, 160)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addGap(170, 170, 170))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combo_Serviço, 0, 250, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(btn_add_Serviço, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt_ValorServiço, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(combo_Técnico, 0, 200, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(btn_Add_Técnico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btn_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btn_Apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btn_Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_OS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_DataOs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_StatusOs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_IdCli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Add_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Aparelho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Defeito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_Serviço, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add_Serviço, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ValorServiço, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Técnico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Add_Técnico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combo_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_ClienteActionPerformed

    private void combo_StatusOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_StatusOsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_StatusOsActionPerformed

    private void btn_add_ServiçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_ServiçoActionPerformed
        // TODO add your handling code here:
        Tela_Serviços servico = new Tela_Serviços();
        servico.setVisible(true);
    }//GEN-LAST:event_btn_add_ServiçoActionPerformed

    private void btn_Add_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Add_ClienteActionPerformed

    private void btn_ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ImprimirActionPerformed

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
        Busca_OS();
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void btn_Add_TécnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add_TécnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Add_TécnicoActionPerformed

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        // TODO add your handling code here:
        new Trocar_Painel(Painel_Desktop, new Tela_Home());
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void tabelaOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaOSMouseClicked
        // TODO add your handling code here:
        int set = tabelaOS.getSelectedRow();
        txt_OS.setText(tabelaOS.getModel().getValueAt(set, 0).toString());
        txt_DataOs.setText(tabelaOS.getModel().getValueAt(set, 1).toString());
        combo_StatusOs.setSelectedItem(tabelaOS.getModel().getValueAt(set, 2).toString());
        txt_Aparelho.setText(tabelaOS.getModel().getValueAt(set, 3).toString());
        txt_Defeito.setText(tabelaOS.getModel().getValueAt(set, 4).toString());
        combo_Serviço.setSelectedItem(tabelaOS.getModel().getValueAt(set, 5).toString());
        txt_ValorServiço.setText(tabelaOS.getModel().getValueAt(set, 6).toString());
        combo_Técnico.setSelectedItem(tabelaOS.getModel().getValueAt(set, 7).toString());
        txt_IdCli.setText(tabelaOS.getModel().getValueAt(set, 8).toString());
        combo_Cliente.setSelectedItem(tabelaOS.getModel().getValueAt(set, 9).toString());

        btn_Cadastrar.setEnabled(true);
    }//GEN-LAST:event_tabelaOSMouseClicked

    private void txt_IdCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IdCliKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdCliKeyPressed

    private void txt_IdCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IdCliKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdCliKeyReleased

    private void txt_IdCliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_IdCliFocusGained
    }//GEN-LAST:event_txt_IdCliFocusGained

    private void txt_IdCliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_IdCliFocusLost
    }//GEN-LAST:event_txt_IdCliFocusLost

    private void combo_ClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_ClientePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        Popular_Cliente();
    }//GEN-LAST:event_combo_ClientePopupMenuWillBecomeInvisible

    private void combo_ClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo_ClienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_ClienteKeyReleased

    private void combo_ServiçoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_ServiçoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:   
        Popular_Serviço();
    }//GEN-LAST:event_combo_ServiçoPopupMenuWillBecomeInvisible

    private void combo_ServiçoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo_ServiçoKeyReleased

    }//GEN-LAST:event_combo_ServiçoKeyReleased

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        // TODO add your handling code here:
        btn_Cadastrar.setEnabled(true);
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    private void btn_ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ApagarActionPerformed
        // TODO add your handling code here:
        btn_Cadastrar.setEnabled(true);
    }//GEN-LAST:event_btn_ApagarActionPerformed

    private void combo_ServiçoPopupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_ServiçoPopupMenuCanceled
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_ServiçoPopupMenuCanceled

    private void combo_ServiçoPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_ServiçoPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        if (combo_Serviço.isPopupVisible()) {
            modelServiços = controllerServiços.getServiçosController(combo_Serviço.getSelectedItem().toString());
        }
        txt_ValorServiço.setText(String.valueOf(modelServiços.getValor_servico()));
    }//GEN-LAST:event_combo_ServiçoPopupMenuWillBecomeVisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btn_Add_Cliente;
    private rojerusan.RSButtonMetro btn_Add_Técnico;
    private rojerusan.RSButtonMetro btn_Apagar;
    private rojerusan.RSButtonMetro btn_Atualizar;
    private rojerusan.RSButtonMetro btn_Cadastrar;
    private rojerusan.RSButtonMetro btn_Imprimir;
    private rojerusan.RSButtonMetro btn_Pesquisar;
    private rojerusan.RSButtonMetro btn_add_Serviço;
    private javax.swing.JComboBox<String> combo_Cliente;
    public static javax.swing.JComboBox<String> combo_Serviço;
    private javax.swing.JComboBox<String> combo_StatusOs;
    private javax.swing.JComboBox<String> combo_Técnico;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    public static javax.swing.JTable tabelaOS;
    private javax.swing.JTextField txt_Aparelho;
    private javax.swing.JTextField txt_DataOs;
    private javax.swing.JTextField txt_Defeito;
    private javax.swing.JTextField txt_IdCli;
    private javax.swing.JTextField txt_OS;
    private javax.swing.JTextField txt_ValorServiço;
    // End of variables declaration//GEN-END:variables
}
