/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lineup.view;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siqueira
 */
public class Tela_Vendas extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Vendas
     */
    public Tela_Vendas() {
        initComponents();
        //txt_Desc_Prod.setText("0");
        //Data();
    }

//    private void Data() {
//        Date data = new Date();
//        SimpleDateFormat Formato_Data = new SimpleDateFormat("dd/MM/yyyy");
//        txt_data.setText(Formato_Data.format(data));
//    }
    
    private String Calcular_Produtos() {
        Double soma = 0.0;
        for (int i = 0; i < tabelaprodutos.getRowCount(); i++) {
            soma += Double.parseDouble(tabelaprodutos.getValueAt(i, 4).toString());
        }
        return soma.toString();
    }

    private String Calcular_Itens() {
        Double item = 0.0;
        for (int i = 0; i < tabelaprodutos.getRowCount(); i++) {
            item += Double.parseDouble(tabelaprodutos.getValueAt(i, 2).toString());
        }
        return item.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_Usuário = new javax.swing.JLabel();
        rSButtonMetro2 = new rsbuttom.RSButtonMetro();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaprodutos = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_Adicionar_item = new rojerusan.RSButtonMetro();
        jLabel2 = new javax.swing.JLabel();
        lbl_Itens = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_ValorTotal_Venda = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_Qtde_Prod = new javax.swing.JTextField();
        txt_nome_prod = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_data = new javax.swing.JTextField();
        btn_Cancelar = new rojerusan.RSButtonMetro();
        btn_Finalizar = new rojerusan.RSButtonMetro();
        btn_Novo = new rojerusan.RSButtonMetro();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txt_Id_Prod = new javax.swing.JTextField();
        txt_ValorTotal_Prod = new javax.swing.JTextField();
        txt_Valor_Un = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LINEUP SYSTEM");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Tela_Venda"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        lbl_Usuário.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Usuário.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Usuário.setText("VENDEDOR");

        rSButtonMetro2.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonMetro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Usuário logado.png"))); // NOI18N
        rSButtonMetro2.setColorHover(new java.awt.Color(51, 255, 0));
        rSButtonMetro2.setColorNormal(new java.awt.Color(0, 102, 153));
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(rSButtonMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Usuário)
                .addContainerGap(878, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Usuário, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSButtonMetro2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        tabelaprodutos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tabelaprodutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUTO", "DESCRIÇÃO", "QUANTIDADE", "VALOR UNITÁRIO", "VALOR TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaprodutos.setFocusable(false);
        tabelaprodutos.setGridColor(new java.awt.Color(0, 0, 0));
        tabelaprodutos.setRowHeight(25);
        tabelaprodutos.setRowMargin(0);
        tabelaprodutos.getTableHeader().setReorderingAllowed(false);
        tabelaprodutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaprodutosKeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(tabelaprodutos);
        if (tabelaprodutos.getColumnModel().getColumnCount() > 0) {
            tabelaprodutos.getColumnModel().getColumn(0).setResizable(false);
            tabelaprodutos.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabelaprodutos.getColumnModel().getColumn(1).setResizable(false);
            tabelaprodutos.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabelaprodutos.getColumnModel().getColumn(2).setResizable(false);
            tabelaprodutos.getColumnModel().getColumn(2).setPreferredWidth(100);
            tabelaprodutos.getColumnModel().getColumn(3).setResizable(false);
            tabelaprodutos.getColumnModel().getColumn(3).setPreferredWidth(120);
            tabelaprodutos.getColumnModel().getColumn(4).setResizable(false);
            tabelaprodutos.getColumnModel().getColumn(4).setPreferredWidth(120);
        }

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 50, 650, 360));

        jLabel10.setBackground(new java.awt.Color(0, 66, 109));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CÓD. PRODUTO:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 66, 109));
        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("VALOR UNITÁRIO:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 66, 109));
        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("QUANTIDADE:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));

        jLabel14.setBackground(new java.awt.Color(0, 66, 109));
        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("VALOR:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        btn_Adicionar_item.setBackground(new java.awt.Color(255, 153, 0));
        btn_Adicionar_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Add_Produto_32px.png"))); // NOI18N
        btn_Adicionar_item.setText("Adicionar");
        btn_Adicionar_item.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        btn_Adicionar_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Adicionar_itemActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Adicionar_item, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 160, 40));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Itens:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, -1, -1));

        lbl_Itens.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        lbl_Itens.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Itens.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Itens.setText("0");
        jPanel1.add(lbl_Itens, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 430, 40, -1));

        jLabel13.setBackground(new java.awt.Color(0, 66, 109));
        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DESCRIÇÃO DO PRODUTO:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        txt_ValorTotal_Venda.setEditable(false);
        txt_ValorTotal_Venda.setBackground(new java.awt.Color(153, 255, 153));
        txt_ValorTotal_Venda.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        txt_ValorTotal_Venda.setForeground(new java.awt.Color(0, 102, 153));
        txt_ValorTotal_Venda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_ValorTotal_Venda.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_ValorTotal_Venda, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, 240, 40));

        jLabel16.setBackground(new java.awt.Color(0, 66, 109));
        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("VALOR TOTAL:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, -1, -1));

        txt_Qtde_Prod.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        txt_Qtde_Prod.setForeground(new java.awt.Color(0, 102, 153));
        txt_Qtde_Prod.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Qtde_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Qtde_Prod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Qtde_ProdKeyReleased(evt);
            }
        });
        jPanel1.add(txt_Qtde_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 150, 40));

        txt_nome_prod.setBackground(new java.awt.Color(204, 255, 255));
        txt_nome_prod.setFont(new java.awt.Font("Berlin Sans FB", 2, 24)); // NOI18N
        txt_nome_prod.setForeground(new java.awt.Color(0, 102, 153));
        txt_nome_prod.setText(" Selecione um Produto...");
        txt_nome_prod.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_nome_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_nome_prodMouseClicked(evt);
            }
        });
        txt_nome_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nome_prodActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nome_prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 730, 40));

        jLabel18.setBackground(new java.awt.Color(0, 66, 109));
        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nº da Venda:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 102, 153));
        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 30));

        jLabel5.setBackground(new java.awt.Color(0, 66, 109));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data da Venda:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        txt_data.setEditable(false);
        txt_data.setBackground(new java.awt.Color(255, 255, 255));
        txt_data.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txt_data.setForeground(new java.awt.Color(0, 102, 153));
        txt_data.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 190, 30));

        btn_Cancelar.setBackground(new java.awt.Color(255, 0, 0));
        btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Cancelar_32px.png"))); // NOI18N
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 160, 40));

        btn_Finalizar.setBackground(new java.awt.Color(0, 204, 102));
        btn_Finalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Venda_32px.png"))); // NOI18N
        btn_Finalizar.setText("Finalizar ");
        btn_Finalizar.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        btn_Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FinalizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, 160, 40));

        btn_Novo.setBackground(new java.awt.Color(0, 153, 204));
        btn_Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Add_32px.png"))); // NOI18N
        btn_Novo.setText("Novo");
        btn_Novo.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, 160, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 980, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 980, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 980, -1));

        txt_Id_Prod.setEditable(false);
        txt_Id_Prod.setBackground(new java.awt.Color(255, 255, 255));
        txt_Id_Prod.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        txt_Id_Prod.setForeground(new java.awt.Color(0, 102, 153));
        txt_Id_Prod.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Id_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_Id_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 160, 40));

        txt_ValorTotal_Prod.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        txt_ValorTotal_Prod.setForeground(new java.awt.Color(0, 102, 153));
        txt_ValorTotal_Prod.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_ValorTotal_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_ValorTotal_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 150, 40));

        txt_Valor_Un.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        txt_Valor_Un.setForeground(new java.awt.Color(0, 102, 153));
        txt_Valor_Un.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Valor_Un.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_Valor_Un, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 150, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons50px/LINEUP_LOGO.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 260, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed

    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FinalizarActionPerformed
        Desconto_Venda desconto = new Desconto_Venda();
        desconto.setVisible(true);
    }//GEN-LAST:event_btn_FinalizarActionPerformed

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed

    }//GEN-LAST:event_btn_NovoActionPerformed

    private void txt_nome_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nome_prodActionPerformed
    }//GEN-LAST:event_txt_nome_prodActionPerformed

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed

    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void txt_nome_prodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nome_prodMouseClicked
        txt_nome_prod.setText(null);
        BuscaProdutos prod = new BuscaProdutos();
        prod.setVisible(true);
    }//GEN-LAST:event_txt_nome_prodMouseClicked

    private void btn_Adicionar_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Adicionar_itemActionPerformed
        // Estabelecendo as restriçoes para adicionar os itens na tabela
        if (txt_Id_Prod.getText().equals("")) {
            if (txt_nome_prod.getText().equals("Selecione um Produto...")) {
                if (txt_Qtde_Prod.getText().equals("")) {
                    if (txt_Valor_Un.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Nenhum produto selecionado, Favor selecionar um produto!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                    }
                }
            }
        } else {
            if (txt_Qtde_Prod.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campo Quantidade não pode conter letras ou ser deixado em branco!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            } else {
                DefaultTableModel produtos = (DefaultTableModel) tabelaprodutos.getModel();
                Object[] dados = {txt_Id_Prod.getText(), txt_nome_prod.getText(), txt_Qtde_Prod.getText(), txt_Valor_Un.getText(), txt_ValorTotal_Prod.getText()};
                produtos.addRow(dados);

                //Setar campos como Nulo (Limpar Campos)
                txt_Id_Prod.setText(null);
                txt_nome_prod.setText(null);
                txt_Qtde_Prod.setText(null);
                txt_Valor_Un.setText(null);
                txt_ValorTotal_Prod.setText(null);
            }
        }
        txt_ValorTotal_Venda.setText(Calcular_Produtos());
        lbl_Itens.setText(Calcular_Itens());
        txt_nome_prod.setText("Selecione um Produto...");
    }//GEN-LAST:event_btn_Adicionar_itemActionPerformed

    private void txt_Qtde_ProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Qtde_ProdKeyReleased
        // TODO add your handling code here:
        float valortotal;
        valortotal = Float.parseFloat(txt_Valor_Un.getText()) * Integer.parseInt(txt_Qtde_Prod.getText());
        txt_ValorTotal_Prod.setText(String.valueOf(valortotal));
    }//GEN-LAST:event_txt_Qtde_ProdKeyReleased

    private void tabelaprodutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaprodutosKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tabelaprodutosKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btn_Adicionar_item;
    private rojerusan.RSButtonMetro btn_Cancelar;
    private rojerusan.RSButtonMetro btn_Finalizar;
    private rojerusan.RSButtonMetro btn_Novo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lbl_Itens;
    public static javax.swing.JLabel lbl_Usuário;
    private rsbuttom.RSButtonMetro rSButtonMetro2;
    private javax.swing.JTable tabelaprodutos;
    public static javax.swing.JTextField txt_Id_Prod;
    public static javax.swing.JTextField txt_Qtde_Prod;
    public static javax.swing.JTextField txt_ValorTotal_Prod;
    public static javax.swing.JTextField txt_ValorTotal_Venda;
    public static javax.swing.JTextField txt_Valor_Un;
    private javax.swing.JTextField txt_data;
    public static javax.swing.JTextField txt_nome_prod;
    // End of variables declaration//GEN-END:variables
}
