/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lineup.view;

import br.com.lineup.controller.ControllerFornecedor;
import br.com.lineup.model.ModelFornecedor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siqueira
 */
public class Tela_Fornecedor extends javax.swing.JFrame {

    ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
    ModelFornecedor modelFornecedor = new ModelFornecedor();
    ArrayList<ModelFornecedor> listaModelFornecedores = new ArrayList<>();

    /**
     * Creates new form Tela_Fornecedor
     */
    public Tela_Fornecedor() {
        initComponents();
        busca_fornecedor();
    }

    private void busca_fornecedor() {
        listaModelFornecedores = controllerFornecedor.getListaFornecedorController();
        DefaultTableModel tabela = (DefaultTableModel) tabelafornecedor.getModel();
        tabela.setNumRows(0);

        int tam_lista = listaModelFornecedores.size();
        for (int i = 0; i < tam_lista; i++) {
            tabela.addRow(new Object[]{
                listaModelFornecedores.get(i).getIdfornecedor(),
                listaModelFornecedores.get(i).getNomefornecedor(),
                listaModelFornecedores.get(i).getRazaosocial(),
                listaModelFornecedores.get(i).getNomefantasia(),
                listaModelFornecedores.get(i).getEndereco(),
                listaModelFornecedores.get(i).getComplemento(),
                listaModelFornecedores.get(i).getBairro(),
                listaModelFornecedores.get(i).getCidade(),
                listaModelFornecedores.get(i).getUf(),
                listaModelFornecedores.get(i).getCNPJ(),
                listaModelFornecedores.get(i).getEmail(),
                listaModelFornecedores.get(i).getTelefone(),
                listaModelFornecedores.get(i).getCelular(),});
        }
    }

    
    private void Combo_Fornecedor() {
        listaModelFornecedores = controllerFornecedor.getListaFornecedorController();
        Tela_Produtos.combo_Fornecedor.removeAllItems();
        for (int i = 0; i < listaModelFornecedores.size(); i++) {
            Tela_Produtos.combo_Fornecedor.addItem(listaModelFornecedores.get(i).getNomefantasia());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSButtonMetro2 = new rsbuttom.RSButtonMetro();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        rSButtonMetro1 = new rojerusan.RSButtonMetro();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelafornecedor = new javax.swing.JTable();
        btn_Cadastrar = new rojerusan.RSButtonMetro();
        btn_Atualizar = new rojerusan.RSButtonMetro();
        btn_Apagar = new rojerusan.RSButtonMetro();
        txt_Id_Forne = new javax.swing.JTextField();
        combo_UF_Forne = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_Nome_Forne = new javax.swing.JTextField();
        txt_NomeFant_Forne = new javax.swing.JTextField();
        txt_End_Forne = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_Razao_Forne = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Fone_Forne = new javax.swing.JFormattedTextField();
        txt_Comp_Forne = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_Bairro_Forne = new javax.swing.JTextField();
        txt_Cidade_Forne = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Email_Forne = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_CNPJ = new javax.swing.JFormattedTextField();
        txt_Celular_Forne = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gerenciar Fornecedores");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons50px/Cliente_50px.png"))); // NOI18N

        rSButtonMetro2.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonMetro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Close.png"))); // NOI18N
        rSButtonMetro2.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetro2.setColorNormal(new java.awt.Color(0, 102, 153));
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 381, Short.MAX_VALUE)
                .addComponent(rSButtonMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(rSButtonMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 102, 153));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 153));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 251, 730, -1));

        jLabel11.setBackground(new java.awt.Color(0, 66, 109));
        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 153));
        jLabel11.setText("Pesquisar Fornecedor:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 91, -1, 30));

        jTextField5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 91, 510, 30));

        rSButtonMetro1.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Busca_24px.png"))); // NOI18N
        jPanel1.add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 91, 40, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 102, 153));
        jSeparator3.setForeground(new java.awt.Color(0, 102, 153));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 542, 730, -1));

        tabelafornecedor.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tabelafornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Razão Social", "Nome Fantasia", "Endereço", "Complemento", "Bairro", "Cidade", "Estado", "CNPJ", "Email", "Telefone", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelafornecedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelafornecedor.setRowHeight(25);
        tabelafornecedor.getTableHeader().setReorderingAllowed(false);
        tabelafornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelafornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelafornecedor);
        if (tabelafornecedor.getColumnModel().getColumnCount() > 0) {
            tabelafornecedor.getColumnModel().getColumn(0).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabelafornecedor.getColumnModel().getColumn(1).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabelafornecedor.getColumnModel().getColumn(2).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(2).setPreferredWidth(200);
            tabelafornecedor.getColumnModel().getColumn(3).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(3).setPreferredWidth(200);
            tabelafornecedor.getColumnModel().getColumn(4).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(4).setPreferredWidth(150);
            tabelafornecedor.getColumnModel().getColumn(5).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(5).setPreferredWidth(150);
            tabelafornecedor.getColumnModel().getColumn(6).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(6).setPreferredWidth(150);
            tabelafornecedor.getColumnModel().getColumn(7).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(7).setPreferredWidth(150);
            tabelafornecedor.getColumnModel().getColumn(8).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(8).setPreferredWidth(100);
            tabelafornecedor.getColumnModel().getColumn(9).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(9).setPreferredWidth(120);
            tabelafornecedor.getColumnModel().getColumn(10).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(10).setPreferredWidth(150);
            tabelafornecedor.getColumnModel().getColumn(11).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(11).setPreferredWidth(120);
            tabelafornecedor.getColumnModel().getColumn(12).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(12).setPreferredWidth(120);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 131, 730, 110));

        btn_Cadastrar.setBackground(new java.awt.Color(0, 204, 102));
        btn_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Adicionar_32px.png"))); // NOI18N
        btn_Cadastrar.setText("Cadastrar");
        btn_Cadastrar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 558, 140, 40));

        btn_Atualizar.setBackground(new java.awt.Color(0, 153, 204));
        btn_Atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Atualizar_32px.png"))); // NOI18N
        btn_Atualizar.setText("Atualizar");
        btn_Atualizar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(btn_Atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 558, 140, 40));

        btn_Apagar.setBackground(new java.awt.Color(255, 0, 0));
        btn_Apagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Deletar_32px.png"))); // NOI18N
        btn_Apagar.setText("Apagar");
        btn_Apagar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ApagarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Apagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 558, 140, 40));

        txt_Id_Forne.setEditable(false);
        txt_Id_Forne.setBackground(new java.awt.Color(255, 255, 255));
        txt_Id_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Id_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Id_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Id_Forne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Id_ForneActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Id_Forne, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 290, 128, 30));

        combo_UF_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        combo_UF_Forne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        combo_UF_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        combo_UF_Forne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_UF_ForneActionPerformed(evt);
            }
        });
        jPanel1.add(combo_UF_Forne, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 430, 104, 30));

        jLabel10.setBackground(new java.awt.Color(0, 66, 109));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("Razão Social:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 260, 104, -1));

        jLabel20.setBackground(new java.awt.Color(0, 66, 109));
        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 153));
        jLabel20.setText("Endereço:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 330, 77, -1));

        jLabel26.setBackground(new java.awt.Color(0, 66, 109));
        jLabel26.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 153));
        jLabel26.setText("Telefone (F):");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 104, -1));

        txt_Nome_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Nome_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Nome_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_Nome_Forne, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 290, 311, 30));

        txt_NomeFant_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_NomeFant_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_NomeFant_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_NomeFant_Forne, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 360, 230, 30));

        txt_End_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_End_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_End_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_End_Forne, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 360, 230, 30));

        jLabel27.setBackground(new java.awt.Color(0, 66, 109));
        jLabel27.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 153));
        jLabel27.setText("Celular:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 470, 68, -1));

        txt_Razao_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Razao_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Razao_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_Razao_Forne, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 290, 255, 30));

        jLabel5.setBackground(new java.awt.Color(0, 66, 109));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("*Código:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 260, 67, -1));

        txt_Fone_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        try {
            txt_Fone_Forne.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_Fone_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(txt_Fone_Forne, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 225, 30));

        txt_Comp_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Comp_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Comp_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_Comp_Forne, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 360, 230, 30));

        jLabel7.setBackground(new java.awt.Color(0, 66, 109));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("Nome Fantasia:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 330, 124, -1));

        jLabel24.setBackground(new java.awt.Color(0, 66, 109));
        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 153));
        jLabel24.setText("Email:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 470, 58, -1));

        jLabel25.setBackground(new java.awt.Color(0, 66, 109));
        jLabel25.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 153));
        jLabel25.setText("*CNPJ:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 400, 69, -1));

        jLabel21.setBackground(new java.awt.Color(0, 66, 109));
        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 153));
        jLabel21.setText("Complemento:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 331, 120, -1));

        jLabel22.setBackground(new java.awt.Color(0, 66, 109));
        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 153));
        jLabel22.setText("Bairro:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 400, 69, -1));

        txt_Bairro_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Bairro_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Bairro_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_Bairro_Forne, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 430, 214, 30));

        txt_Cidade_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Cidade_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Cidade_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Cidade_Forne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Cidade_ForneActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Cidade_Forne, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 430, 209, 30));

        jLabel23.setBackground(new java.awt.Color(0, 66, 109));
        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 153));
        jLabel23.setText("Cidade:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 400, 81, -1));

        jLabel6.setBackground(new java.awt.Color(0, 66, 109));
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("*Estado:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 401, 80, -1));

        txt_Email_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Email_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Email_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_Email_Forne, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 500, 249, 30));

        jLabel9.setBackground(new java.awt.Color(0, 66, 109));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("*Nome:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 260, 62, -1));

        txt_CNPJ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        try {
            txt_CNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_CNPJ.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(txt_CNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 430, 139, 30));

        txt_Celular_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        try {
            txt_Celular_Forne.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_Celular_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(txt_Celular_Forne, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 500, 218, 30));

        jLabel28.setBackground(new java.awt.Color(0, 66, 109));
        jLabel28.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 153));
        jLabel28.setText("Limpar");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 568, 58, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
// Adicionando dados do Fornecedor no banco a partir das informações das caixas de texto:
        modelFornecedor.setNomefornecedor(this.txt_Nome_Forne.getText());
        modelFornecedor.setRazaosocial(this.txt_Razao_Forne.getText());
        modelFornecedor.setNomefantasia(this.txt_NomeFant_Forne.getText());
        modelFornecedor.setEndereco(this.txt_End_Forne.getText());
        modelFornecedor.setComplemento(this.txt_Comp_Forne.getText());
        modelFornecedor.setBairro(this.txt_Bairro_Forne.getText());
        modelFornecedor.setCidade(this.txt_Cidade_Forne.getText());
        modelFornecedor.setUf(this.combo_UF_Forne.getSelectedItem().toString());
        modelFornecedor.setCNPJ(this.txt_CNPJ.getText());
        modelFornecedor.setEmail(this.txt_Email_Forne.getText());
        modelFornecedor.setTelefone(this.txt_Fone_Forne.getText());
        modelFornecedor.setCelular(this.txt_Celular_Forne.getText());

        // Condição para testar se as informações foram gravadas no banco:
        if (controllerFornecedor.salvarFornecedorController(modelFornecedor) > 0) {
            JOptionPane.showMessageDialog(this, "Fornecedor cadastrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao tentar cadastrar Fornecedor!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

        //Setando os campos como nulo, após efetuado o cadastro:
        txt_Nome_Forne.setText(null);
        txt_Razao_Forne.setText(null);
        txt_NomeFant_Forne.setText(null);
        txt_End_Forne.setText(null);
        txt_Comp_Forne.setText(null);
        txt_Bairro_Forne.setText(null);
        txt_Cidade_Forne.setText(null);
        combo_UF_Forne.setSelectedItem(null);
        txt_CNPJ.setText(null);
        txt_Email_Forne.setText(null);
        txt_Fone_Forne.setText(null);
        txt_Celular_Forne.setText(null);
        txt_Id_Forne.setText(null);

        busca_fornecedor();
        Combo_Fornecedor();
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void tabelafornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelafornecedorMouseClicked
        // TODO add your handling code here:
        int set = tabelafornecedor.getSelectedRow();
        txt_Nome_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 1).toString());
        txt_Razao_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 2).toString());
        txt_NomeFant_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 3).toString());
        txt_End_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 4).toString());
        txt_Comp_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 5).toString());
        txt_Bairro_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 6).toString());
        txt_Cidade_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 7).toString());
        combo_UF_Forne.setSelectedItem(tabelafornecedor.getModel().getValueAt(set, 8).toString());
        txt_CNPJ.setText(tabelafornecedor.getModel().getValueAt(set, 9).toString());
        txt_Email_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 10).toString());
        txt_Fone_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 11).toString());
        txt_Celular_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 12).toString());
        txt_Id_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 0).toString());
    }//GEN-LAST:event_tabelafornecedorMouseClicked

    private void txt_Id_ForneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Id_ForneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Id_ForneActionPerformed

    private void combo_UF_ForneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_UF_ForneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_UF_ForneActionPerformed

    private void txt_Cidade_ForneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Cidade_ForneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Cidade_ForneActionPerformed

    private void btn_ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ApagarActionPerformed
        // TODO add your handling code here:
        int del = tabelafornecedor.getSelectedRow();
        int id_forne = (int) tabelafornecedor.getValueAt(del, 0);
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja deletar este Fornecedor?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            //Condição para testar se houve sucesso ou erro na exclusão:
            try {
                if (controllerFornecedor.excluirFornecedorController(id_forne)) {
                    JOptionPane.showMessageDialog(this, "Fornecedor deletado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao tentar deletar fornecedor!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

        //Setando os campos como nulo
        txt_Nome_Forne.setText(null);
        txt_Razao_Forne.setText(null);
        txt_NomeFant_Forne.setText(null);
        txt_End_Forne.setText(null);
        txt_Comp_Forne.setText(null);
        txt_Bairro_Forne.setText(null);
        txt_Cidade_Forne.setText(null);
        combo_UF_Forne.setSelectedItem(null);
        txt_CNPJ.setText(null);
        txt_Email_Forne.setText(null);
        txt_Fone_Forne.setText(null);
        txt_Celular_Forne.setText(null);

        busca_fornecedor();
    }//GEN-LAST:event_btn_ApagarActionPerformed

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        //Setando os campos como nulo, após efetuado o cadastro:
        txt_Nome_Forne.setText(null);
        txt_Razao_Forne.setText(null);
        txt_NomeFant_Forne.setText(null);
        txt_End_Forne.setText(null);
        txt_Comp_Forne.setText(null);
        txt_Bairro_Forne.setText(null);
        txt_Cidade_Forne.setText(null);
        combo_UF_Forne.setSelectedItem(null);
        txt_CNPJ.setText(null);
        txt_Email_Forne.setText(null);
        txt_Fone_Forne.setText(null);
        txt_Celular_Forne.setText(null);
        txt_Id_Forne.setText(null);

        busca_fornecedor();
    }//GEN-LAST:event_jLabel28MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Fornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btn_Apagar;
    private rojerusan.RSButtonMetro btn_Atualizar;
    private rojerusan.RSButtonMetro btn_Cadastrar;
    private javax.swing.JComboBox<String> combo_UF_Forne;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField5;
    private rojerusan.RSButtonMetro rSButtonMetro1;
    private rsbuttom.RSButtonMetro rSButtonMetro2;
    private javax.swing.JTable tabelafornecedor;
    private javax.swing.JTextField txt_Bairro_Forne;
    private javax.swing.JFormattedTextField txt_CNPJ;
    private javax.swing.JFormattedTextField txt_Celular_Forne;
    private javax.swing.JTextField txt_Cidade_Forne;
    private javax.swing.JTextField txt_Comp_Forne;
    private javax.swing.JTextField txt_Email_Forne;
    private javax.swing.JTextField txt_End_Forne;
    private javax.swing.JFormattedTextField txt_Fone_Forne;
    private javax.swing.JTextField txt_Id_Forne;
    private javax.swing.JTextField txt_NomeFant_Forne;
    private javax.swing.JTextField txt_Nome_Forne;
    private javax.swing.JTextField txt_Razao_Forne;
    // End of variables declaration//GEN-END:variables
}
