/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lineup.view;

import br.com.lineup.controller.ControllerFornecedor;
import br.com.lineup.model.ModelFornecedor;
import static br.com.lineup.view.MENU.Painel_Desktop;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siqueira
 */
public class Tela_Fornecedores extends javax.swing.JPanel {

    ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
    ModelFornecedor modelFornecedor = new ModelFornecedor();
    ArrayList<ModelFornecedor> listaModelFornecedores = new ArrayList<>();

    /**
     * Creates new form Tela_Fornecedores
     */
    public Tela_Fornecedores() {
        initComponents();
        busca_fornecedor();
        
    }

    private void busca_fornecedor() {
        listaModelFornecedores = controllerFornecedor.getListaFornecedorController();
        DefaultTableModel tabela = (DefaultTableModel) tabelafornecedor.getModel();
        tabela.setNumRows(0);

        int tam_lista = listaModelFornecedores.size();
        for (int i = 0; i < tam_lista; i++) {
            tabela.addRow(new Object[]{
                listaModelFornecedores.get(i).getIdfornecedor(),
                listaModelFornecedores.get(i).getNomefornecedor(),
                listaModelFornecedores.get(i).getRazaosocial(),
                listaModelFornecedores.get(i).getNomefantasia(),
                listaModelFornecedores.get(i).getEndereco(),
                listaModelFornecedores.get(i).getComplemento(),
                listaModelFornecedores.get(i).getBairro(),
                listaModelFornecedores.get(i).getCidade(),
                listaModelFornecedores.get(i).getUf(),
                listaModelFornecedores.get(i).getCNPJ(),
                listaModelFornecedores.get(i).getEmail(),
                listaModelFornecedores.get(i).getTelefone(),
                listaModelFornecedores.get(i).getCelular(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        rSButtonMetro1 = new rojerusan.RSButtonMetro();
        btn_Cadastrar = new rojerusan.RSButtonMetro();
        jLabel6 = new javax.swing.JLabel();
        txt_Email_Forne = new javax.swing.JTextField();
        btn_Atualizar = new rojerusan.RSButtonMetro();
        jLabel9 = new javax.swing.JLabel();
        txt_CNPJ = new javax.swing.JFormattedTextField();
        txt_Celular_Forne = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_NomeFant_Forne = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_Fone_Forne = new javax.swing.JFormattedTextField();
        txt_Comp_Forne = new javax.swing.JTextField();
        btn_Apagar = new rojerusan.RSButtonMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelafornecedor = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_Bairro_Forne = new javax.swing.JTextField();
        txt_Cidade_Forne = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rSButtonMetro5 = new rsbuttom.RSButtonMetro();
        txt_Id_Forne = new javax.swing.JTextField();
        combo_UF_Forne = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txt_Nome_Forne = new javax.swing.JTextField();
        txt_End_Forne = new javax.swing.JTextField();
        txt_Razao_Forne = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(0, 66, 109));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("Nome Fantasia:");

        jLabel24.setBackground(new java.awt.Color(0, 66, 109));
        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 153));
        jLabel24.setText("Email:");

        jLabel25.setBackground(new java.awt.Color(0, 66, 109));
        jLabel25.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 153));
        jLabel25.setText("*CNPJ:");

        jLabel11.setBackground(new java.awt.Color(0, 66, 109));
        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 153));
        jLabel11.setText("Pesquisar Fornecedor:");

        jTextField5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        rSButtonMetro1.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Busca_24px.png"))); // NOI18N

        btn_Cadastrar.setBackground(new java.awt.Color(0, 204, 102));
        btn_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Adicionar_32px.png"))); // NOI18N
        btn_Cadastrar.setText("Cadastrar");
        btn_Cadastrar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 66, 109));
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("*Estado:");

        txt_Email_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Email_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Email_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btn_Atualizar.setBackground(new java.awt.Color(0, 153, 204));
        btn_Atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Atualizar_32px.png"))); // NOI18N
        btn_Atualizar.setText("Atualizar");
        btn_Atualizar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 66, 109));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("*Nome:");

        txt_CNPJ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        try {
            txt_CNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_CNPJ.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        txt_Celular_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        try {
            txt_Celular_Forne.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_Celular_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel10.setBackground(new java.awt.Color(0, 66, 109));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("Razão Social:");

        jLabel26.setBackground(new java.awt.Color(0, 66, 109));
        jLabel26.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 153));
        jLabel26.setText("Telefone (F):");

        txt_NomeFant_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_NomeFant_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_NomeFant_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel27.setBackground(new java.awt.Color(0, 66, 109));
        jLabel27.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 153));
        jLabel27.setText("Celular:");

        jSeparator2.setBackground(new java.awt.Color(0, 102, 153));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 153));

        txt_Fone_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        try {
            txt_Fone_Forne.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_Fone_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        txt_Comp_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Comp_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Comp_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btn_Apagar.setBackground(new java.awt.Color(255, 0, 0));
        btn_Apagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Deletar_32px.png"))); // NOI18N
        btn_Apagar.setText("Apagar");
        btn_Apagar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ApagarActionPerformed(evt);
            }
        });

        tabelafornecedor.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tabelafornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Razão Social", "Nome Fantasia", "Endereço", "Complemento", "Bairro", "Cidade", "Estado", "CNPJ", "Email", "Telefone", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelafornecedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelafornecedor.setRowHeight(25);
        tabelafornecedor.getTableHeader().setReorderingAllowed(false);
        tabelafornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelafornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelafornecedor);
        if (tabelafornecedor.getColumnModel().getColumnCount() > 0) {
            tabelafornecedor.getColumnModel().getColumn(0).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabelafornecedor.getColumnModel().getColumn(1).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabelafornecedor.getColumnModel().getColumn(2).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(2).setPreferredWidth(170);
            tabelafornecedor.getColumnModel().getColumn(3).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(3).setPreferredWidth(170);
            tabelafornecedor.getColumnModel().getColumn(4).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(4).setPreferredWidth(150);
            tabelafornecedor.getColumnModel().getColumn(5).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(5).setPreferredWidth(150);
            tabelafornecedor.getColumnModel().getColumn(6).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(6).setPreferredWidth(150);
            tabelafornecedor.getColumnModel().getColumn(7).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(7).setPreferredWidth(150);
            tabelafornecedor.getColumnModel().getColumn(8).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(8).setPreferredWidth(100);
            tabelafornecedor.getColumnModel().getColumn(9).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(9).setPreferredWidth(150);
            tabelafornecedor.getColumnModel().getColumn(10).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(10).setPreferredWidth(200);
            tabelafornecedor.getColumnModel().getColumn(11).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(11).setPreferredWidth(120);
            tabelafornecedor.getColumnModel().getColumn(12).setResizable(false);
            tabelafornecedor.getColumnModel().getColumn(12).setPreferredWidth(120);
        }

        jLabel21.setBackground(new java.awt.Color(0, 66, 109));
        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 153));
        jLabel21.setText("Complemento:");

        jLabel22.setBackground(new java.awt.Color(0, 66, 109));
        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 153));
        jLabel22.setText("Bairro:");

        txt_Bairro_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Bairro_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Bairro_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_Cidade_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Cidade_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Cidade_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Cidade_Forne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Cidade_ForneActionPerformed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(0, 66, 109));
        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 153));
        jLabel23.setText("Cidade:");

        jSeparator3.setBackground(new java.awt.Color(0, 102, 153));
        jSeparator3.setForeground(new java.awt.Color(0, 102, 153));

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Gerenciar Fornecedores");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons50px/Cliente_50px.png"))); // NOI18N

        rSButtonMetro5.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonMetro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Close.png"))); // NOI18N
        rSButtonMetro5.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetro5.setColorNormal(new java.awt.Color(0, 102, 153));
        rSButtonMetro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro5rSButtonMetro2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButtonMetro5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(rSButtonMetro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txt_Id_Forne.setEditable(false);
        txt_Id_Forne.setBackground(new java.awt.Color(255, 255, 255));
        txt_Id_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Id_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Id_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Id_Forne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Id_ForneActionPerformed(evt);
            }
        });

        combo_UF_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        combo_UF_Forne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        combo_UF_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        combo_UF_Forne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_UF_ForneActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(0, 66, 109));
        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 153));
        jLabel20.setText("Endereço:");

        txt_Nome_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Nome_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Nome_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_End_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_End_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_End_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_Razao_Forne.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Razao_Forne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Razao_Forne.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel5.setBackground(new java.awt.Color(0, 66, 109));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("*Código:");

        jLabel28.setBackground(new java.awt.Color(0, 66, 109));
        jLabel28.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 153));
        jLabel28.setText("Limpar");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(212, 212, 212)
                .addComponent(btn_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_Apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_NomeFant_Forne)
                                .addGap(20, 20, 20)
                                .addComponent(txt_End_Forne)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(129, 129, 129)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(170, 170, 170)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(120, 120, 120))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_Comp_Forne)
                                .addGap(10, 10, 10))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(16, 16, 16)
                                .addComponent(jTextField5)
                                .addGap(0, 0, 0)
                                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_Id_Forne)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                        .addGap(79, 79, 79)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_Nome_Forne)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                        .addGap(267, 267, 267)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                        .addGap(151, 151, 151))
                                    .addComponent(txt_Razao_Forne)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_Bairro_Forne)
                                        .addGap(20, 20, 20))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(165, 165, 165)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(152, 152, 152))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_Cidade_Forne, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                        .addGap(24, 24, 24)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(combo_UF_Forne, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(44, 44, 44)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(70, 70, 70))
                                    .addComponent(txt_CNPJ)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(211, 211, 211))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_Email_Forne)
                                        .addGap(20, 20, 20)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(139, 139, 139))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_Fone_Forne)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Celular_Forne)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(150, 150, 150)))))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Id_Forne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_Nome_Forne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_Razao_Forne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel20)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_NomeFant_Forne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_End_Forne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Comp_Forne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Bairro_Forne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Cidade_Forne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_UF_Forne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(jLabel26)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Email_Forne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Celular_Forne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_Fone_Forne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel28))
                .addGap(7, 7, 7))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
        // Adicionando dados do Fornecedor no banco a partir das informações das caixas de texto:
        modelFornecedor.setNomefornecedor(this.txt_Nome_Forne.getText());
        modelFornecedor.setRazaosocial(this.txt_Razao_Forne.getText());
        modelFornecedor.setNomefantasia(this.txt_NomeFant_Forne.getText());
        modelFornecedor.setEndereco(this.txt_End_Forne.getText());
        modelFornecedor.setComplemento(this.txt_Comp_Forne.getText());
        modelFornecedor.setBairro(this.txt_Bairro_Forne.getText());
        modelFornecedor.setCidade(this.txt_Cidade_Forne.getText());
        modelFornecedor.setUf(this.combo_UF_Forne.getSelectedItem().toString());
        modelFornecedor.setCNPJ(this.txt_CNPJ.getText());
        modelFornecedor.setEmail(this.txt_Email_Forne.getText());
        modelFornecedor.setTelefone(this.txt_Fone_Forne.getText());
        modelFornecedor.setCelular(this.txt_Celular_Forne.getText());

        // Condição para testar se as informações foram gravadas no banco:
        if (controllerFornecedor.salvarFornecedorController(modelFornecedor) > 0) {
            JOptionPane.showMessageDialog(this, "Fornecedor cadastrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao tentar cadastrar Fornecedor!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

        //Setando os campos como nulo, após efetuado o cadastro:
        txt_Nome_Forne.setText(null);
        txt_Razao_Forne.setText(null);
        txt_NomeFant_Forne.setText(null);
        txt_End_Forne.setText(null);
        txt_Comp_Forne.setText(null);
        txt_Bairro_Forne.setText(null);
        txt_Cidade_Forne.setText(null);
        combo_UF_Forne.setSelectedItem(null);
        txt_CNPJ.setText(null);
        txt_Email_Forne.setText(null);
        txt_Fone_Forne.setText(null);
        txt_Celular_Forne.setText(null);

        busca_fornecedor();
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void txt_Cidade_ForneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Cidade_ForneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Cidade_ForneActionPerformed

    private void rSButtonMetro5rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro5rSButtonMetro2ActionPerformed
        // TODO add your handling code here:
        new Trocar_Painel(Painel_Desktop, new Tela_Home());
    }//GEN-LAST:event_rSButtonMetro5rSButtonMetro2ActionPerformed

    private void txt_Id_ForneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Id_ForneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Id_ForneActionPerformed

    private void combo_UF_ForneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_UF_ForneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_UF_ForneActionPerformed

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        // TODO add your handling code here:

        busca_fornecedor();
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    private void btn_ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ApagarActionPerformed
        // TODO add your handling code here:
        int del = tabelafornecedor.getSelectedRow();
        int id_forne = (int) tabelafornecedor.getValueAt(del, 0);
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja deletar este Fornecedor?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            //Condição para testar se houve sucesso ou erro na exclusão:
            try {
                if (controllerFornecedor.excluirFornecedorController(id_forne)) {
                    JOptionPane.showMessageDialog(this, "Fornecedor deletado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao tentar deletar fornecedor!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

        //Setando os campos como nulo
        txt_Nome_Forne.setText(null);
        txt_Razao_Forne.setText(null);
        txt_NomeFant_Forne.setText(null);
        txt_End_Forne.setText(null);
        txt_Comp_Forne.setText(null);
        txt_Bairro_Forne.setText(null);
        txt_Cidade_Forne.setText(null);
        combo_UF_Forne.setSelectedItem(null);
        txt_CNPJ.setText(null);
        txt_Email_Forne.setText(null);
        txt_Fone_Forne.setText(null);
        txt_Celular_Forne.setText(null);

        busca_fornecedor();
    }//GEN-LAST:event_btn_ApagarActionPerformed

    private void tabelafornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelafornecedorMouseClicked
        // TODO add your handling code here:
        int set = tabelafornecedor.getSelectedRow();
        txt_Nome_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 1).toString());
        txt_Razao_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 2).toString());
        txt_NomeFant_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 3).toString());
        txt_End_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 4).toString());
        txt_Comp_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 5).toString());
        txt_Bairro_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 6).toString());
        txt_Cidade_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 7).toString());
        combo_UF_Forne.setSelectedItem(tabelafornecedor.getModel().getValueAt(set, 8).toString());
        txt_CNPJ.setText(tabelafornecedor.getModel().getValueAt(set, 9).toString());
        txt_Email_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 10).toString());
        txt_Fone_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 11).toString());
        txt_Celular_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 12).toString());
        txt_Id_Forne.setText(tabelafornecedor.getModel().getValueAt(set, 0).toString());
    }//GEN-LAST:event_tabelafornecedorMouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        //Setando os campos como nulo, após efetuado o cadastro:
        txt_Nome_Forne.setText(null);
        txt_Razao_Forne.setText(null);
        txt_NomeFant_Forne.setText(null);
        txt_End_Forne.setText(null);
        txt_Comp_Forne.setText(null);
        txt_Bairro_Forne.setText(null);
        txt_Cidade_Forne.setText(null);
        combo_UF_Forne.setSelectedItem(null);
        txt_CNPJ.setText(null);
        txt_Email_Forne.setText(null);
        txt_Fone_Forne.setText(null);
        txt_Celular_Forne.setText(null);

        busca_fornecedor();
    }//GEN-LAST:event_jLabel28MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btn_Apagar;
    private rojerusan.RSButtonMetro btn_Atualizar;
    private rojerusan.RSButtonMetro btn_Cadastrar;
    private javax.swing.JComboBox<String> combo_UF_Forne;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField5;
    private rojerusan.RSButtonMetro rSButtonMetro1;
    private rsbuttom.RSButtonMetro rSButtonMetro5;
    private javax.swing.JTable tabelafornecedor;
    private javax.swing.JTextField txt_Bairro_Forne;
    private javax.swing.JFormattedTextField txt_CNPJ;
    private javax.swing.JFormattedTextField txt_Celular_Forne;
    private javax.swing.JTextField txt_Cidade_Forne;
    private javax.swing.JTextField txt_Comp_Forne;
    private javax.swing.JTextField txt_Email_Forne;
    private javax.swing.JTextField txt_End_Forne;
    private javax.swing.JFormattedTextField txt_Fone_Forne;
    private javax.swing.JTextField txt_Id_Forne;
    private javax.swing.JTextField txt_NomeFant_Forne;
    private javax.swing.JTextField txt_Nome_Forne;
    private javax.swing.JTextField txt_Razao_Forne;
    // End of variables declaration//GEN-END:variables
}
