package br.com.lineup.view;

import br.com.lineup.controller.ControllerFornecedor;
import br.com.lineup.controller.ControllerGrupo;
import br.com.lineup.controller.ControllerProduto;
import br.com.lineup.controller.ControllerUnidade;
import br.com.lineup.model.ModelFornecedor;
import br.com.lineup.model.ModelGrupo;
import br.com.lineup.model.ModelProduto;
import br.com.lineup.model.ModelUnidade;
import static br.com.lineup.view.MENU.Painel_Desktop;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siqueira
 */
public class Tela_Produtos extends javax.swing.JPanel {

    ControllerProduto controllerProduto = new ControllerProduto();
    ModelProduto modelProduto = new ModelProduto();
    ArrayList<ModelProduto> listaModelProduto = new ArrayList<>();

    ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
    ModelFornecedor modelFornecedor = new ModelFornecedor();
    ArrayList<ModelFornecedor> listaModelFornecedores = new ArrayList<>();

    ControllerUnidade controllerUnidade = new ControllerUnidade();
    ModelUnidade modelUnidade = new ModelUnidade();
    ArrayList<ModelUnidade> listaModelUnidades = new ArrayList<>();
    
    ControllerGrupo controllerGrupo = new ControllerGrupo();
    ModelGrupo modelGrupo = new ModelGrupo();
    ArrayList<ModelGrupo> listaModelGrupo = new ArrayList<>();
    /**
     * Creates new form Tela_Produtos
     */
    public Tela_Produtos() {
        initComponents();
        txt_Cod_Barras_Prod.setText("0");
        busca_produto();
        Combo_Fornecedor();
        Combo_Grupo();
        Combo_Unidade();
    }

    private void busca_produto() {
        listaModelProduto = controllerProduto.getListaProdutoController();
        DefaultTableModel tabela = (DefaultTableModel) tabelaproduto.getModel();
        tabela.setNumRows(0);

        int tam_lista = listaModelProduto.size();
        for (int i = 0; i < tam_lista; i++) {
            tabela.addRow(new Object[]{
                listaModelProduto.get(i).getIdproduto(),
                listaModelProduto.get(i).getCodbarras(),
                listaModelProduto.get(i).getNomeproduto(),
                listaModelProduto.get(i).getQuantidade(),
                listaModelProduto.get(i).getUnidadecomercial(),
                listaModelProduto.get(i).getGrupo(),
                listaModelProduto.get(i).getMarca(),
                listaModelProduto.get(i).getFornecedor(),
                listaModelProduto.get(i).getPrecocusto(),
                listaModelProduto.get(i).getPrecovenda(),});

        }
    }

    private void Combo_Fornecedor() {
        listaModelFornecedores = controllerFornecedor.getListaFornecedorController();
        combo_Fornecedor.removeAllItems();
        for (int i = 0; i < listaModelFornecedores.size(); i++) {
            combo_Fornecedor.addItem(listaModelFornecedores.get(i).getNomefantasia());
        }
    }
    
    private void Combo_Unidade() {
        listaModelUnidades = controllerUnidade.getListaUnidadeController();
        combo_Unidade.removeAllItems();
        for (int i = 0; i < listaModelUnidades.size(); i++) {
            combo_Unidade.addItem(listaModelUnidades.get(i).getSigla_unidade());
        }
    }
    
    private void Combo_Grupo() {
        listaModelGrupo = controllerGrupo.getListaGrupoController();
        combo_Grupo.removeAllItems();
        for (int i = 0; i < listaModelGrupo.size(); i++) {
            combo_Grupo.addItem(listaModelGrupo.get(i).getDescricao());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSButtonMetro5 = new rsbuttom.RSButtonMetro();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        rSButtonMetro1 = new rojerusan.RSButtonMetro();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaproduto = new javax.swing.JTable();
        btn_Add_Forne = new rojerusan.RSButtonMetro();
        btn_Atualizar = new rojerusan.RSButtonMetro();
        btn_Apagar = new rojerusan.RSButtonMetro();
        txt_ID_prod = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_Marca_Prod = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Qtde_Prod = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_Nome_Prod = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        combo_Fornecedor = new javax.swing.JComboBox<>();
        btn_Cadastrar = new rojerusan.RSButtonMetro();
        jLabel12 = new javax.swing.JLabel();
        combo_Grupo = new javax.swing.JComboBox<>();
        btn_Add_Grupo = new rojerusan.RSButtonMetro();
        txt_PreçoVenda_Prod = new javax.swing.JTextField();
        txt_PreçoCusto_Prod = new javax.swing.JTextField();
        combo_Unidade = new javax.swing.JComboBox<>();
        btn_Add_Unid = new rojerusan.RSButtonMetro();
        txt_Cod_Barras_Prod = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gerenciar Produtos");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons50px/Produto_50px.png"))); // NOI18N

        rSButtonMetro5.setBackground(new java.awt.Color(0, 102, 153));
        rSButtonMetro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Close.png"))); // NOI18N
        rSButtonMetro5.setColorHover(new java.awt.Color(204, 0, 0));
        rSButtonMetro5.setColorNormal(new java.awt.Color(0, 102, 153));
        rSButtonMetro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButtonMetro5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(rSButtonMetro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel11.setBackground(new java.awt.Color(0, 66, 109));
        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 153));
        jLabel11.setText("Pesquisar Produto:");

        jTextField5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        rSButtonMetro1.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Busca_24px.png"))); // NOI18N

        tabelaproduto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tabelaproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Código de Barras", "Descrição", "Quantidade", "Unidade", "Grupo", "Marca", "Fornecedor", "Preço de Custo", "Preço de Venda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaproduto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaproduto.setRowHeight(25);
        tabelaproduto.getTableHeader().setReorderingAllowed(false);
        tabelaproduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaprodutoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaproduto);
        if (tabelaproduto.getColumnModel().getColumnCount() > 0) {
            tabelaproduto.getColumnModel().getColumn(0).setResizable(false);
            tabelaproduto.getColumnModel().getColumn(0).setPreferredWidth(150);
            tabelaproduto.getColumnModel().getColumn(1).setResizable(false);
            tabelaproduto.getColumnModel().getColumn(1).setPreferredWidth(170);
            tabelaproduto.getColumnModel().getColumn(2).setResizable(false);
            tabelaproduto.getColumnModel().getColumn(2).setPreferredWidth(250);
            tabelaproduto.getColumnModel().getColumn(3).setResizable(false);
            tabelaproduto.getColumnModel().getColumn(3).setPreferredWidth(100);
            tabelaproduto.getColumnModel().getColumn(4).setResizable(false);
            tabelaproduto.getColumnModel().getColumn(4).setPreferredWidth(100);
            tabelaproduto.getColumnModel().getColumn(5).setResizable(false);
            tabelaproduto.getColumnModel().getColumn(5).setPreferredWidth(150);
            tabelaproduto.getColumnModel().getColumn(6).setResizable(false);
            tabelaproduto.getColumnModel().getColumn(6).setPreferredWidth(150);
            tabelaproduto.getColumnModel().getColumn(7).setResizable(false);
            tabelaproduto.getColumnModel().getColumn(7).setPreferredWidth(250);
            tabelaproduto.getColumnModel().getColumn(8).setResizable(false);
            tabelaproduto.getColumnModel().getColumn(8).setPreferredWidth(170);
            tabelaproduto.getColumnModel().getColumn(9).setResizable(false);
            tabelaproduto.getColumnModel().getColumn(9).setPreferredWidth(170);
        }

        btn_Add_Forne.setBackground(new java.awt.Color(255, 255, 255));
        btn_Add_Forne.setForeground(new java.awt.Color(0, 66, 109));
        btn_Add_Forne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Add_24px.png"))); // NOI18N
        btn_Add_Forne.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        btn_Add_Forne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add_ForneActionPerformed(evt);
            }
        });

        btn_Atualizar.setBackground(new java.awt.Color(0, 153, 204));
        btn_Atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Atualizar_32px.png"))); // NOI18N
        btn_Atualizar.setText("Atualizar");
        btn_Atualizar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });

        btn_Apagar.setBackground(new java.awt.Color(255, 0, 0));
        btn_Apagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Deletar_32px.png"))); // NOI18N
        btn_Apagar.setText("Apagar");
        btn_Apagar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ApagarActionPerformed(evt);
            }
        });

        txt_ID_prod.setEditable(false);
        txt_ID_prod.setBackground(new java.awt.Color(255, 255, 255));
        txt_ID_prod.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_ID_prod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_ID_prod.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel20.setBackground(new java.awt.Color(0, 66, 109));
        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 153));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Marca:");

        txt_Marca_Prod.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Marca_Prod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Marca_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel5.setBackground(new java.awt.Color(0, 66, 109));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("*Código:");

        jLabel7.setBackground(new java.awt.Color(0, 66, 109));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Quantidade:");

        txt_Qtde_Prod.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Qtde_Prod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Qtde_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel9.setBackground(new java.awt.Color(0, 66, 109));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Cód. Barras:");

        jLabel10.setBackground(new java.awt.Color(0, 66, 109));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Nome do Produto:");

        txt_Nome_Prod.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Nome_Prod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Nome_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel8.setBackground(new java.awt.Color(0, 66, 109));
        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Unidade:");

        jSeparator2.setBackground(new java.awt.Color(0, 102, 153));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 153));

        jLabel21.setBackground(new java.awt.Color(0, 66, 109));
        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 153));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Fornecedor:");

        jLabel22.setBackground(new java.awt.Color(0, 66, 109));
        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 153));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Preço de Venda:");

        jLabel23.setBackground(new java.awt.Color(0, 66, 109));
        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 153));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Preço de Custo:");

        jSeparator3.setBackground(new java.awt.Color(0, 102, 153));
        jSeparator3.setForeground(new java.awt.Color(0, 102, 153));

        combo_Fornecedor.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        combo_Fornecedor.setMaximumRowCount(5);
        combo_Fornecedor.setBorder(null);

        btn_Cadastrar.setBackground(new java.awt.Color(0, 204, 102));
        btn_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons32px/Adicionar_32px.png"))); // NOI18N
        btn_Cadastrar.setText("Cadastrar");
        btn_Cadastrar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 66, 109));
        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Grupo:");

        combo_Grupo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        combo_Grupo.setMaximumRowCount(5);
        combo_Grupo.setBorder(null);

        btn_Add_Grupo.setBackground(new java.awt.Color(255, 255, 255));
        btn_Add_Grupo.setForeground(new java.awt.Color(0, 66, 109));
        btn_Add_Grupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Add_24px.png"))); // NOI18N
        btn_Add_Grupo.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        btn_Add_Grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add_GrupoActionPerformed(evt);
            }
        });

        txt_PreçoVenda_Prod.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_PreçoVenda_Prod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_PreçoVenda_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_PreçoCusto_Prod.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_PreçoCusto_Prod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_PreçoCusto_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        combo_Unidade.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        combo_Unidade.setMaximumRowCount(5);
        combo_Unidade.setBorder(null);

        btn_Add_Unid.setBackground(new java.awt.Color(255, 255, 255));
        btn_Add_Unid.setForeground(new java.awt.Color(0, 66, 109));
        btn_Add_Unid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lineup/icons24px/Add_24px.png"))); // NOI18N
        btn_Add_Unid.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        btn_Add_Unid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add_UnidActionPerformed(evt);
            }
        });

        txt_Cod_Barras_Prod.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_Cod_Barras_Prod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_Cod_Barras_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel24.setBackground(new java.awt.Color(0, 66, 109));
        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 153));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Limpar");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo_Fornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10)
                                .addComponent(btn_Add_Forne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(170, 170, 170)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_PreçoVenda_Prod)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(74, 74, 74))
                            .addComponent(txt_PreçoCusto_Prod)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txt_Qtde_Prod)
                                .addGap(1, 1, 1))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_ID_prod))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(combo_Unidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(10, 10, 10)
                                        .addComponent(btn_Add_Unid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(combo_Grupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(244, 244, 244)))
                                .addGap(10, 10, 10)
                                .addComponent(btn_Add_Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Marca_Prod)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(139, 139, 139))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(128, 128, 128))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_Cod_Barras_Prod)
                                        .addGap(22, 22, 22)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(239, 239, 239))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_Nome_Prod)
                                        .addGap(1, 1, 1))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)
                        .addGap(39, 39, 39)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ID_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Cod_Barras_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Nome_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(jLabel20))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Qtde_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Unidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Add_Unid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Add_Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Marca_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel21))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Add_Forne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_PreçoVenda_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_PreçoCusto_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_Apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Add_ForneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add_ForneActionPerformed
        Tela_Fornecedor fornec = new Tela_Fornecedor();
        fornec.setVisible(true);
    }//GEN-LAST:event_btn_Add_ForneActionPerformed

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
        // TODO add your handling code here:
        modelProduto.setNomeproduto(this.txt_Nome_Prod.getText());
        modelProduto.setCodbarras(this.txt_Cod_Barras_Prod.getText());
        modelProduto.setQuantidade(Integer.parseInt(this.txt_Qtde_Prod.getText()));
        modelProduto.setUnidadecomercial(this.combo_Unidade.getSelectedItem().toString());
        modelProduto.setGrupo(this.combo_Grupo.getSelectedItem().toString());
        modelProduto.setMarca(this.txt_Marca_Prod.getText());
        modelProduto.setFornecedor(this.combo_Fornecedor.getSelectedItem().toString());
        modelProduto.setPrecovenda(Double.parseDouble(this.txt_PreçoVenda_Prod.getText()));
        modelProduto.setPrecocusto(Double.parseDouble(this.txt_PreçoCusto_Prod.getText()));

        if (controllerProduto.salvarProdutoController(modelProduto) >= 0) {
            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar Produto!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        // Setar campos como nulo:
        txt_ID_prod.setText(null);
        txt_Cod_Barras_Prod.setText(null);
        txt_Nome_Prod.setText(null);
        txt_Qtde_Prod.setText(null);
        txt_PreçoCusto_Prod.setText(null);
        txt_PreçoVenda_Prod.setText(null);
        txt_Marca_Prod.setText(null);
        combo_Fornecedor.setSelectedItem(null);
        combo_Grupo.setSelectedItem(null);
        combo_Unidade.setSelectedItem(null);
        
        busca_produto();
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void btn_Add_GrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add_GrupoActionPerformed
        // TODO add your handling code here:
        Tela_AddGrupo grupo = new Tela_AddGrupo();
        grupo.setVisible(true);
    }//GEN-LAST:event_btn_Add_GrupoActionPerformed

    private void btn_Add_UnidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add_UnidActionPerformed
        // TODO add your handling code here:
        Tela_AddUnidade unidade = new Tela_AddUnidade();
        unidade.setVisible(true);

    }//GEN-LAST:event_btn_Add_UnidActionPerformed

    private void rSButtonMetro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro5ActionPerformed
        // TODO add your handling code here:
        new Trocar_Painel(Painel_Desktop, new Tela_Home());
    }//GEN-LAST:event_rSButtonMetro5ActionPerformed

    private void tabelaprodutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaprodutoMouseClicked
        // TODO add your handling code here:
        int set = tabelaproduto.getSelectedRow();
        txt_ID_prod.setText(tabelaproduto.getModel().getValueAt(set, 0).toString());
        txt_Cod_Barras_Prod.setText(tabelaproduto.getModel().getValueAt(set, 1).toString());
        txt_Nome_Prod.setText(tabelaproduto.getModel().getValueAt(set, 2).toString());
        txt_Qtde_Prod.setText(tabelaproduto.getModel().getValueAt(set, 3).toString());
        combo_Unidade.setSelectedItem(tabelaproduto.getModel().getValueAt(set, 4).toString());
        combo_Grupo.setSelectedItem(tabelaproduto.getModel().getValueAt(set, 5).toString());
        txt_Marca_Prod.setText(tabelaproduto.getModel().getValueAt(set, 6).toString());
        combo_Fornecedor.setSelectedItem(tabelaproduto.getModel().getValueAt(set, 7).toString());
        txt_PreçoCusto_Prod.setText(tabelaproduto.getModel().getValueAt(set, 8).toString());
        txt_PreçoVenda_Prod.setText(tabelaproduto.getModel().getValueAt(set, 9).toString());

        // Setar o botão cadastrar como desabilitado, para não poder cadastrar outra pessoa com a mesma ID:
        btn_Cadastrar.setEnabled(false);
    }//GEN-LAST:event_tabelaprodutoMouseClicked

    private void btn_ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ApagarActionPerformed
        // Apagar dados do produto a partir do ID:
        int del = tabelaproduto.getSelectedRow();
        int id_prod = (int) tabelaproduto.getValueAt(del, 0);
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja deletar este Produto?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            //Condição para testar se houve sucesso ou erro na exclusão:
            try {
                if (controllerProduto.excluirProdutoController(id_prod)) {
                    JOptionPane.showMessageDialog(this, "Produto deletado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao tentar deletar produto!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Este produto não pode ser deletado, pois já está vinculado a uma Venda!");
            }
        }
        // Setar campos como nulo:
        txt_ID_prod.setText(null);
        txt_Cod_Barras_Prod.setText(null);
        txt_Nome_Prod.setText(null);
        txt_Qtde_Prod.setText(null);
        txt_PreçoCusto_Prod.setText(null);
        txt_PreçoVenda_Prod.setText(null);
        txt_Marca_Prod.setText(null);
        combo_Fornecedor.setSelectedItem(null);
        combo_Grupo.setSelectedItem(null);
        combo_Unidade.setSelectedItem(null);

        // Chamar o método de busca de clientes da tabela:
        busca_produto();

        btn_Cadastrar.setEnabled(true);
    }//GEN-LAST:event_btn_ApagarActionPerformed

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // Setar campos como nulo:
        txt_ID_prod.setText(null);
        txt_Cod_Barras_Prod.setText(null);
        txt_Nome_Prod.setText(null);
        txt_Qtde_Prod.setText(null);
        txt_PreçoCusto_Prod.setText(null);
        txt_PreçoVenda_Prod.setText(null);
        txt_Marca_Prod.setText(null);
        combo_Fornecedor.setSelectedItem(null);
        combo_Grupo.setSelectedItem(null);
        combo_Unidade.setSelectedItem(null);

        busca_produto();
        btn_Cadastrar.setEnabled(true);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        // TODO add your handling code here:
//        int alterar = this.tabelaproduto.getSelectedRow();
//        int prod = this.tabelaproduto.getValueAt(alterar, 0)
    }//GEN-LAST:event_btn_AtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btn_Add_Forne;
    private rojerusan.RSButtonMetro btn_Add_Grupo;
    private rojerusan.RSButtonMetro btn_Add_Unid;
    private rojerusan.RSButtonMetro btn_Apagar;
    private rojerusan.RSButtonMetro btn_Atualizar;
    private rojerusan.RSButtonMetro btn_Cadastrar;
    public static javax.swing.JComboBox<String> combo_Fornecedor;
    private javax.swing.JComboBox<String> combo_Grupo;
    private javax.swing.JComboBox<String> combo_Unidade;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField5;
    private rojerusan.RSButtonMetro rSButtonMetro1;
    private rsbuttom.RSButtonMetro rSButtonMetro5;
    private javax.swing.JTable tabelaproduto;
    private javax.swing.JTextField txt_Cod_Barras_Prod;
    private javax.swing.JTextField txt_ID_prod;
    private javax.swing.JTextField txt_Marca_Prod;
    private javax.swing.JTextField txt_Nome_Prod;
    private javax.swing.JTextField txt_PreçoCusto_Prod;
    private javax.swing.JTextField txt_PreçoVenda_Prod;
    private javax.swing.JTextField txt_Qtde_Prod;
    // End of variables declaration//GEN-END:variables
}
